// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: ui

#include "../ui.h"

void ui_Equipment_screen_init(void)
{
ui_Equipment = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Equipment, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Equipment,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Equipment, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_pad_left(ui_Equipment, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Equipment, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Equipment, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Equipment, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Equipment, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Equipment, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Setting_header2 = ui_Setting_header_create(ui_Equipment);
lv_obj_set_x( ui_Setting_header2, 0 );
lv_obj_set_y( ui_Setting_header2, 0 );

lv_label_set_text(ui_comp_get_child(ui_Setting_header2, UI_COMP_SETTING_HEADER_SETTING_TITLE),"EQUIPMENT");





ui_equipment_settings_container = lv_obj_create(ui_Equipment);
lv_obj_remove_style_all(ui_equipment_settings_container);
lv_obj_set_width( ui_equipment_settings_container, 300);
lv_obj_set_height( ui_equipment_settings_container, 190);
lv_obj_set_x( ui_equipment_settings_container, 0 );
lv_obj_set_y( ui_equipment_settings_container, -6 );
lv_obj_set_align( ui_equipment_settings_container, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_equipment_settings_container,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_equipment_settings_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_equipment_settings_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_heat_type_container = lv_obj_create(ui_equipment_settings_container);
lv_obj_remove_style_all(ui_heat_type_container);
lv_obj_set_width( ui_heat_type_container, 300);
lv_obj_set_height( ui_heat_type_container, 45);
lv_obj_set_align( ui_heat_type_container, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_heat_type_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label36 = lv_label_create(ui_heat_type_container);
lv_obj_set_width( ui_Label36, 130);
lv_obj_set_height( ui_Label36, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label36, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label36,"HEATING");
lv_obj_set_style_text_align(ui_Label36, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heat_type = lv_dropdown_create(ui_heat_type_container);
lv_dropdown_set_options( ui_heat_type, "NONE\nFANCOIL\nVALVE" );
lv_obj_set_width( ui_heat_type, 150);
lv_obj_set_height( ui_heat_type, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_heat_type, 150 );
lv_obj_set_y( ui_heat_type, 0 );
lv_obj_set_align( ui_heat_type, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_heat_type, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



ui_cool_type_container = lv_obj_create(ui_equipment_settings_container);
lv_obj_remove_style_all(ui_cool_type_container);
lv_obj_set_width( ui_cool_type_container, 300);
lv_obj_set_height( ui_cool_type_container, 45);
lv_obj_set_align( ui_cool_type_container, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_cool_type_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label37 = lv_label_create(ui_cool_type_container);
lv_obj_set_width( ui_Label37, 130);
lv_obj_set_height( ui_Label37, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label37, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label37,"COOLING");
lv_obj_set_style_text_align(ui_Label37, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cool_type = lv_dropdown_create(ui_cool_type_container);
lv_dropdown_set_options( ui_cool_type, "NONE\nFANCOIL\nVALVE" );
lv_obj_set_width( ui_cool_type, 150);
lv_obj_set_height( ui_cool_type, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cool_type, 150 );
lv_obj_set_y( ui_cool_type, 0 );
lv_obj_set_align( ui_cool_type, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_cool_type, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



ui_makeup_air_container = lv_obj_create(ui_equipment_settings_container);
lv_obj_remove_style_all(ui_makeup_air_container);
lv_obj_set_width( ui_makeup_air_container, 300);
lv_obj_set_height( ui_makeup_air_container, 50);
lv_obj_set_align( ui_makeup_air_container, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_makeup_air_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label38 = lv_label_create(ui_makeup_air_container);
lv_obj_set_width( ui_Label38, 130);
lv_obj_set_height( ui_Label38, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label38, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label38,"MAKEUP AIR");
lv_obj_set_style_text_align(ui_Label38, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_makeup_air_switch = lv_switch_create(ui_makeup_air_container);
lv_obj_set_width( ui_makeup_air_switch, 50);
lv_obj_set_height( ui_makeup_air_switch, 25);
lv_obj_set_x( ui_makeup_air_switch, 150 );
lv_obj_set_y( ui_makeup_air_switch, 0 );
lv_obj_set_align( ui_makeup_air_switch, LV_ALIGN_LEFT_MID );


lv_obj_add_event_cb(ui_comp_get_child(ui_Setting_header2, UI_COMP_SETTING_HEADER_SETTING_BACK_BUTTON), ui_event_Setting_header2_Setting_back_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_comp_get_child(ui_Setting_header2, UI_COMP_SETTING_HEADER_SETTING_ACCEPT_BUTTON), ui_event_Setting_header2_Setting_accept_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Equipment, ui_event_Equipment, LV_EVENT_ALL, NULL);

}
