// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: ui

#include "../ui.h"

void ui_Temp_limits_screen_init(void)
{
ui_Temp_limits = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Temp_limits, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Temp_limits,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Temp_limits, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_pad_left(ui_Temp_limits, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Temp_limits, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Temp_limits, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Temp_limits, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Temp_limits, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Temp_limits, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Thermostat_setting_header2 = ui_Setting_header_create(ui_Temp_limits);
lv_obj_set_x( ui_Thermostat_setting_header2, 0 );
lv_obj_set_y( ui_Thermostat_setting_header2, 0 );

lv_label_set_text(ui_comp_get_child(ui_Thermostat_setting_header2, UI_COMP_SETTING_HEADER_SETTING_TITLE),"TEMP LIMITS");





ui_Container5 = lv_obj_create(ui_Temp_limits);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 300);
lv_obj_set_height( ui_Container5, 190);
lv_obj_set_x( ui_Container5, 0 );
lv_obj_set_y( ui_Container5, -6 );
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_heat_limit_container = lv_obj_create(ui_Container5);
lv_obj_remove_style_all(ui_heat_limit_container);
lv_obj_set_height( ui_heat_limit_container, 160);
lv_obj_set_width( ui_heat_limit_container, LV_SIZE_CONTENT);  /// 2
lv_obj_set_align( ui_heat_limit_container, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_heat_limit_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_heat_limit_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_heat_limit_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_heat_limit_container, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_heat_limit_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_heat_limit_container, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_opa(ui_heat_limit_container, 60, LV_PART_MAIN| LV_STATE_DISABLED);

ui_heat_limit = lv_roller_create(ui_heat_limit_container);
lv_roller_set_options( ui_heat_limit, "64\n65\n66\n67\n68\n69\n70\n71\n72\n73\n74", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_heat_limit, 100);
lv_obj_set_width( ui_heat_limit, LV_SIZE_CONTENT);  /// 50
lv_obj_set_align( ui_heat_limit, LV_ALIGN_TOP_MID );
lv_obj_set_style_text_font(ui_heat_limit, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_heat_limit, lv_color_hex(0xFF9040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_heat_limit, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label28 = lv_label_create(ui_heat_limit_container);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label28, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label28,"MAX HEAT\nSETPOINT");
lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xFF9040), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label28, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Divider5 = lv_obj_create(ui_Container5);
lv_obj_set_width( ui_Divider5, 1);
lv_obj_set_height( ui_Divider5, 140);
lv_obj_set_x( ui_Divider5, 0 );
lv_obj_set_y( ui_Divider5, -3 );
lv_obj_set_align( ui_Divider5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Divider5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Divider5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Divider5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Divider5, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Divider5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Divider5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Divider5, LV_BORDER_SIDE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Override_cool_container1 = lv_obj_create(ui_Container5);
lv_obj_remove_style_all(ui_Override_cool_container1);
lv_obj_set_height( ui_Override_cool_container1, 160);
lv_obj_set_width( ui_Override_cool_container1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Override_cool_container1, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Override_cool_container1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Override_cool_container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Override_cool_container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Override_cool_container1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Override_cool_container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_Override_cool_container1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_opa(ui_Override_cool_container1, 60, LV_PART_MAIN| LV_STATE_DISABLED);

ui_cool_limit = lv_roller_create(ui_Override_cool_container1);
lv_roller_set_options( ui_cool_limit, "64\n65\n66\n67\n68\n69\n70\n71\n72\n73\n74", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_cool_limit, 100);
lv_obj_set_width( ui_cool_limit, LV_SIZE_CONTENT);  /// 50
lv_obj_set_align( ui_cool_limit, LV_ALIGN_TOP_MID );
lv_obj_set_style_text_font(ui_cool_limit, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_cool_limit, lv_color_hex(0x4CAFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_cool_limit, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label29 = lv_label_create(ui_Override_cool_container1);
lv_obj_set_width( ui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label29, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label29, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label29,"MIN COOL\nSETPOINT");
lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x4CAFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label29, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_comp_get_child(ui_Thermostat_setting_header2, UI_COMP_SETTING_HEADER_SETTING_BACK_BUTTON), ui_event_Thermostat_setting_header2_Setting_back_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_comp_get_child(ui_Thermostat_setting_header2, UI_COMP_SETTING_HEADER_SETTING_ACCEPT_BUTTON), ui_event_Thermostat_setting_header2_Setting_accept_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Temp_limits, ui_event_Temp_limits, LV_EVENT_ALL, NULL);

}
