// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: ui

#include "../ui.h"


// COMPONENT Setting header

lv_obj_t *ui_Setting_header_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Setting_header;
cui_Setting_header = lv_obj_create(comp_parent);
lv_obj_set_width( cui_Setting_header, 300);
lv_obj_set_height( cui_Setting_header, 35);
lv_obj_set_align( cui_Setting_header, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( cui_Setting_header, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_Setting_header, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Setting_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_Setting_header, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_Setting_header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_Setting_header, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_Setting_header, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Setting_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Setting_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Setting_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Setting_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Setting_title;
cui_Setting_title = lv_label_create(cui_Setting_header);
lv_obj_set_width( cui_Setting_title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Setting_title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Setting_title, LV_ALIGN_CENTER );
lv_label_set_text(cui_Setting_title,"TITLE");
lv_obj_set_style_text_font(cui_Setting_title, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Setting_back_button;
cui_Setting_back_button = lv_obj_create(cui_Setting_header);
lv_obj_remove_style_all(cui_Setting_back_button);
lv_obj_set_width( cui_Setting_back_button, 35);
lv_obj_set_height( cui_Setting_back_button, 35);
lv_obj_set_align( cui_Setting_back_button, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( cui_Setting_back_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_Setting_back_label;
cui_Setting_back_label = lv_label_create(cui_Setting_back_button);
lv_obj_set_width( cui_Setting_back_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Setting_back_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Setting_back_label, 5 );
lv_obj_set_y( cui_Setting_back_label, 0 );
lv_obj_set_align( cui_Setting_back_label, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_Setting_back_label,"");
lv_obj_set_style_text_font(cui_Setting_back_label, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Setting_accept_button;
cui_Setting_accept_button = lv_obj_create(cui_Setting_header);
lv_obj_remove_style_all(cui_Setting_accept_button);
lv_obj_set_width( cui_Setting_accept_button, 35);
lv_obj_set_height( cui_Setting_accept_button, 35);
lv_obj_set_align( cui_Setting_accept_button, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( cui_Setting_accept_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_Setting_accept_label;
cui_Setting_accept_label = lv_label_create(cui_Setting_accept_button);
lv_obj_set_width( cui_Setting_accept_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Setting_accept_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Setting_accept_label, -5 );
lv_obj_set_y( cui_Setting_accept_label, 0 );
lv_obj_set_align( cui_Setting_accept_label, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_Setting_accept_label,"");
lv_obj_set_style_text_font(cui_Setting_accept_label, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SETTING_HEADER_NUM);
children[UI_COMP_SETTING_HEADER_SETTING_HEADER] = cui_Setting_header;
children[UI_COMP_SETTING_HEADER_SETTING_TITLE] = cui_Setting_title;
children[UI_COMP_SETTING_HEADER_SETTING_BACK_BUTTON] = cui_Setting_back_button;
children[UI_COMP_SETTING_HEADER_SETTING_BACK_BUTTON_SETTING_BACK_LABEL] = cui_Setting_back_label;
children[UI_COMP_SETTING_HEADER_SETTING_ACCEPT_BUTTON] = cui_Setting_accept_button;
children[UI_COMP_SETTING_HEADER_SETTING_ACCEPT_BUTTON_SETTING_ACCEPT_LABEL] = cui_Setting_accept_label;
lv_obj_add_event_cb(cui_Setting_header, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Setting_header, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Setting_header_create_hook(cui_Setting_header);
return cui_Setting_header; 
}

