// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: ui

#include "../ui.h"

void ui_Settings_screen_init(void)
{
ui_Settings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Settings,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Settings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_pad_left(ui_Settings, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Settings, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Settings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Settings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Settings, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Settings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Setting_header1 = ui_Setting_header_create(ui_Settings);
lv_obj_set_x( ui_Setting_header1, 0 );
lv_obj_set_y( ui_Setting_header1, 0 );

lv_label_set_text(ui_comp_get_child(ui_Setting_header1, UI_COMP_SETTING_HEADER_SETTING_TITLE),"SETTINGS");




lv_obj_add_flag( ui_comp_get_child(ui_Setting_header1, UI_COMP_SETTING_HEADER_SETTING_ACCEPT_BUTTON_SETTING_ACCEPT_LABEL), LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_Container3 = lv_obj_create(ui_Settings);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, 300);
lv_obj_set_height( ui_Container3, LV_SIZE_CONTENT);   /// 180
lv_obj_set_x( ui_Container3, 0 );
lv_obj_set_y( ui_Container3, -6 );
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_buttons_left = lv_obj_create(ui_Container3);
lv_obj_remove_style_all(ui_Settings_buttons_left);
lv_obj_set_height( ui_Settings_buttons_left, 165);
lv_obj_set_width( ui_Settings_buttons_left, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Settings_buttons_left, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Settings_buttons_left,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Settings_buttons_left, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Settings_buttons_left, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Settings_buttons_left, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Settings_buttons_left, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Settings_buttons_left, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Settings_buttons_left, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Settings_buttons_left, 17, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Settings_buttons_left, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_equipment_button = lv_btn_create(ui_Settings_buttons_left);
lv_obj_set_width( ui_equipment_button, 140);
lv_obj_set_height( ui_equipment_button, 40);
lv_obj_set_align( ui_equipment_button, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_equipment_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_equipment_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_equipment_button, lv_color_hex(0x44474C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_equipment_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_equipment_button, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_equipment_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_equipment_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label25 = lv_label_create(ui_equipment_button);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"EQUIPMENT");
lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp_limit_button = lv_btn_create(ui_Settings_buttons_left);
lv_obj_set_width( ui_temp_limit_button, 140);
lv_obj_set_height( ui_temp_limit_button, 40);
lv_obj_set_align( ui_temp_limit_button, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_temp_limit_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_temp_limit_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_temp_limit_button, lv_color_hex(0x44474C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_temp_limit_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_temp_limit_button, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_temp_limit_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_temp_limit_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label26 = lv_label_create(ui_temp_limit_button);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label26, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label26,"TEMP LIMITS");
lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_equipment_button2 = lv_btn_create(ui_Settings_buttons_left);
lv_obj_set_width( ui_equipment_button2, 140);
lv_obj_set_height( ui_equipment_button2, 40);
lv_obj_set_align( ui_equipment_button2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_equipment_button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_equipment_button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_equipment_button2, lv_color_hex(0x44474C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_equipment_button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_equipment_button2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_equipment_button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_equipment_button2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label27 = lv_label_create(ui_equipment_button2);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"TEMP OFFSET");
lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Divider4 = lv_obj_create(ui_Container3);
lv_obj_set_width( ui_Divider4, 1);
lv_obj_set_height( ui_Divider4, 155);
lv_obj_set_x( ui_Divider4, 0 );
lv_obj_set_y( ui_Divider4, -3 );
lv_obj_set_align( ui_Divider4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Divider4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Divider4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Divider4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Divider4, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Divider4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Divider4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Divider4, LV_BORDER_SIDE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_buttons_right = lv_obj_create(ui_Container3);
lv_obj_remove_style_all(ui_Settings_buttons_right);
lv_obj_set_height( ui_Settings_buttons_right, 165);
lv_obj_set_width( ui_Settings_buttons_right, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Settings_buttons_right, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Settings_buttons_right,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Settings_buttons_right, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Settings_buttons_right, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Settings_buttons_right, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Settings_buttons_right, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Settings_buttons_right, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Settings_buttons_right, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Settings_buttons_right, 17, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Settings_buttons_right, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_schedule_button2 = lv_btn_create(ui_Settings_buttons_right);
lv_obj_set_width( ui_schedule_button2, 120);
lv_obj_set_height( ui_schedule_button2, 40);
lv_obj_set_align( ui_schedule_button2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_schedule_button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_schedule_button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_schedule_button2, lv_color_hex(0x44474C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_schedule_button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_schedule_button2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_schedule_button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_schedule_button2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label23 = lv_label_create(ui_schedule_button2);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"WIFI");
lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_comp_get_child(ui_Setting_header1, UI_COMP_SETTING_HEADER_SETTING_BACK_BUTTON), ui_event_Setting_header1_Setting_back_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_equipment_button, ui_event_equipment_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_temp_limit_button, ui_event_temp_limit_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_equipment_button2, ui_event_equipment_button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_schedule_button2, ui_event_schedule_button2, LV_EVENT_ALL, NULL);

}
