// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: ui

#ifndef _UI_COMP_SETTING_HEADER_H
#define _UI_COMP_SETTING_HEADER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Setting header
#define UI_COMP_SETTING_HEADER_SETTING_HEADER 0
#define UI_COMP_SETTING_HEADER_SETTING_TITLE 1
#define UI_COMP_SETTING_HEADER_SETTING_BACK_BUTTON 2
#define UI_COMP_SETTING_HEADER_SETTING_BACK_BUTTON_SETTING_BACK_LABEL 3
#define UI_COMP_SETTING_HEADER_SETTING_ACCEPT_BUTTON 4
#define UI_COMP_SETTING_HEADER_SETTING_ACCEPT_BUTTON_SETTING_ACCEPT_LABEL 5
#define _UI_COMP_SETTING_HEADER_NUM 6
lv_obj_t *ui_Setting_header_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
