// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t *ui_Home;
lv_obj_t *ui_Header;
lv_obj_t *ui_Humidity;
lv_obj_t *ui_Humidity_symbol;
lv_obj_t *ui_Humidity_value;
void ui_event_Fan( lv_event_t * e);
lv_obj_t *ui_Fan;
lv_obj_t *ui_Fan_symbol;
lv_obj_t *ui_Fan_value;
lv_obj_t *ui_out_temp;
lv_obj_t *ui_out_symbol;
lv_obj_t *ui_Out_temp_value;
lv_obj_t *ui_Footer;
lv_obj_t *ui_Message;
lv_obj_t *ui_Indoor_Temp;
lv_obj_t *ui_Container3;
lv_obj_t *ui_Indoor_temp_value;
lv_obj_t *ui_Temp_setpoint_container;
lv_obj_t *ui_Setpoint_row;
lv_obj_t *ui_Heat_setpoint_container;
lv_obj_t *ui_Heat_symbol;
lv_obj_t *ui_Heat_setpoint;
lv_obj_t *ui_Cool_setpoint_container;
lv_obj_t *ui_Cool_symbol;
lv_obj_t *ui_Cool_setpoint;
lv_obj_t *ui_Temp_header;
lv_obj_t *ui_Indoor_co2;
lv_obj_t *ui_co2_header;
lv_obj_t *ui_Container4;
lv_obj_t *ui_co2_value;
lv_obj_t *ui_co2_setpoint_container;
lv_obj_t *ui_co2_symbol;
lv_obj_t *ui_co2_target_value;


// SCREEN: ui_Fan_speed_override
void ui_Fan_speed_override_screen_init(void);
lv_obj_t *ui_Fan_speed_override;
lv_obj_t *ui_Setting_header;
void ui_event_Setting_header_Setting_back_button_Setting_back_label( lv_event_t * e);
void ui_event_Setting_header_Setting_accept_button_Setting_accept_label( lv_event_t * e);
lv_obj_t *ui_Container7;
lv_obj_t *ui_Override_speed_container;
lv_obj_t *ui_Fan_override_speed;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Divider;
lv_obj_t *ui_Override_time_container;
lv_obj_t *ui_Override_hrs_container;
lv_obj_t *ui_Fan_override_hrs;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Override_mins_container;
lv_obj_t *ui_Fan_override_mins;
lv_obj_t *ui_Label2;


// SCREEN: ui_Thermostat
void ui_Thermostat_screen_init(void);
lv_obj_t *ui_Thermostat;
lv_obj_t *ui_Thermostat_setting_header;
void ui_event_Thermostat_setting_header_Setting_back_button_Setting_back_label( lv_event_t * e);
void ui_event_Thermostat_setting_header_Setting_accept_button_Setting_accept_label( lv_event_t * e);
lv_obj_t *ui_Container1;
lv_obj_t *ui_Override_heat_container;
lv_obj_t *ui_Heat_override_setpoint;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Override_cool_container;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Cool_override_setpoint;
lv_obj_t *ui_Divider1;
lv_obj_t *ui_Schedule_buttons;
void ui_event_schedule_button( lv_event_t * e);
lv_obj_t *ui_schedule_button;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Container12;
void ui_event_use_ac_button( lv_event_t * e);
lv_obj_t *ui_use_ac_button;
lv_obj_t *ui_Label9;
void ui_event_stop_ac_button( lv_event_t * e);
lv_obj_t *ui_stop_ac_button;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Container10;
void ui_event_off_button( lv_event_t * e);
lv_obj_t *ui_off_button;
lv_obj_t *ui_Label7;
void ui_event_on_button( lv_event_t * e);
lv_obj_t *ui_on_button;
lv_obj_t *ui_Label10;


// SCREEN: ui_CO2
void ui_CO2_screen_init(void);
lv_obj_t *ui_CO2;
lv_obj_t *ui_Thermostat_setting_header1;
void ui_event_Thermostat_setting_header1_Setting_back_button_Setting_back_label( lv_event_t * e);
void ui_event_Thermostat_setting_header1_Setting_accept_button_Setting_accept_label( lv_event_t * e);
lv_obj_t *ui_Container2;
lv_obj_t *ui_Override_speed_container1;
lv_obj_t *ui_co2_target;
lv_obj_t *ui_Container11;
lv_obj_t *ui_co2_symbol1;
lv_obj_t *ui_Label11;


// SCREEN: ui_Schedule
void ui_Schedule_screen_init(void);
lv_obj_t *ui_Schedule;
lv_obj_t *ui_Schedule_header;
void ui_event_Schedule_header_Setting_accept_button_Setting_accept_label( lv_event_t * e);
lv_obj_t *ui_Container14;
lv_obj_t *ui_TabView1;
lv_obj_t *ui_DAY;
lv_obj_t *ui_Day_heat_container;
lv_obj_t *ui_Day_heat_setpoint;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Day_cool_container;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Day_cool_setpoint;
lv_obj_t *ui_Divider2;
lv_obj_t *ui_Day_time_container;
lv_obj_t *ui_Day_hrs_container;
lv_obj_t *ui_Day_hr;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Day_min_container;
lv_obj_t *ui_Day_min;
lv_obj_t *ui_Label17;
lv_obj_t *ui_NIGHT;
lv_obj_t *ui_Night_heat_container;
lv_obj_t *ui_Night_heat_setpoint;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Night_cool_container;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Night_cool_setpoint;
lv_obj_t *ui_Divider3;
lv_obj_t *ui_Night_time_container;
lv_obj_t *ui_Night_hrs_container;
lv_obj_t *ui_Night_hr;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Night_min_container;
lv_obj_t *ui_Night_min;
lv_obj_t *ui_Label20;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Fan( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Fan_speed_override, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Fan_speed_override_screen_init);
}
}
void ui_event_Setting_header_Setting_back_button_Setting_back_label( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
}
}
void ui_event_Setting_header_Setting_accept_button_Setting_accept_label( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
      set_fan_override( e );
}
}
void ui_event_Thermostat_setting_header_Setting_back_button_Setting_back_label( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
}
}
void ui_event_Thermostat_setting_header_Setting_accept_button_Setting_accept_label( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
      set_thermostat_override( e );
}
}
void ui_event_schedule_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Schedule, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Schedule_screen_init);
}
}
void ui_event_use_ac_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_use_ac( e );
}
}
void ui_event_stop_ac_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_stop_ac( e );
}
}
void ui_event_off_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_system_off( e );
}
}
void ui_event_on_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_system_on( e );
}
}
void ui_event_Thermostat_setting_header1_Setting_back_button_Setting_back_label( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
}
}
void ui_event_Thermostat_setting_header1_Setting_accept_button_Setting_accept_label( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
      set_target_co2( e );
}
}
void ui_event_Schedule_header_Setting_accept_button_Setting_accept_label( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Thermostat, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Thermostat_screen_init);
      set_schedule( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Home_screen_init();
ui_Fan_speed_override_screen_init();
ui_Thermostat_screen_init();
ui_CO2_screen_init();
ui_Schedule_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Home);
}
