// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Load_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Boot
void ui_Boot_screen_init(void);
lv_obj_t *ui_Boot;
lv_obj_t *ui_boot_message;
lv_obj_t *ui_boot_error_heading;
lv_obj_t *ui_Container6;
lv_obj_t *ui_boot_error_text;


// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home( lv_event_t * e);
lv_obj_t *ui_Home;
lv_obj_t *ui_Header;
lv_obj_t *ui_Clock_container;
lv_obj_t *ui_clock_value;
lv_obj_t *ui_Humidity;
lv_obj_t *ui_Humidity_symbol;
lv_obj_t *ui_Humidity_value;
void ui_event_Fan( lv_event_t * e);
lv_obj_t *ui_Fan;
lv_obj_t *ui_Fan_symbol;
lv_obj_t *ui_Fan_value;
lv_obj_t *ui_out_temp;
lv_obj_t *ui_out_symbol;
lv_obj_t *ui_Out_temp_value;
void ui_event_settings( lv_event_t * e);
lv_obj_t *ui_settings;
lv_obj_t *ui_settings_symbol;
lv_obj_t *ui_Footer;
lv_obj_t *ui_message_container;
lv_obj_t *ui_message_close;
lv_obj_t *ui_message_text;
lv_obj_t *ui_Indoor_Temp;
void ui_event_indoor_temps_container( lv_event_t * e);
lv_obj_t *ui_indoor_temps_container;
lv_obj_t *ui_Indoor_temp_value;
lv_obj_t *ui_Temp_setpoint_container;
lv_obj_t *ui_Setpoint_row;
lv_obj_t *ui_Heat_setpoint_container;
lv_obj_t *ui_Heat_symbol;
lv_obj_t *ui_Heat_setpoint;
lv_obj_t *ui_Cool_setpoint_container;
lv_obj_t *ui_Cool_symbol;
lv_obj_t *ui_Cool_setpoint;
lv_obj_t *ui_Temp_header;
lv_obj_t *ui_Indoor_co2;
lv_obj_t *ui_co2_header;
void ui_event_co2_container( lv_event_t * e);
lv_obj_t *ui_co2_container;
lv_obj_t *ui_co2_value;
lv_obj_t *ui_co2_setpoint_container;
lv_obj_t *ui_co2_symbol;
lv_obj_t *ui_co2_target_value;


// SCREEN: ui_Fan_speed_override
void ui_Fan_speed_override_screen_init(void);
lv_obj_t *ui_Fan_speed_override;
lv_obj_t *ui_fan_setting_header;
void ui_event_fan_setting_header_Setting_back_button( lv_event_t * e);
void ui_event_fan_setting_header_Setting_accept_button( lv_event_t * e);
lv_obj_t *ui_fan_override_container;
lv_obj_t *ui_Override_speed_container;
lv_obj_t *ui_Fan_override_speed;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Divider;
lv_obj_t *ui_Override_time_container;
lv_obj_t *ui_Override_hrs_container;
lv_obj_t *ui_Fan_override_hrs;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Override_mins_container;
lv_obj_t *ui_Fan_override_mins;
lv_obj_t *ui_Label2;
lv_obj_t *ui_fan_override_secondary_container;
lv_obj_t *ui_Label21;


// SCREEN: ui_Thermostat
void ui_Thermostat_screen_init(void);
void ui_event_Thermostat( lv_event_t * e);
lv_obj_t *ui_Thermostat;
lv_obj_t *ui_Thermostat_setting_header;
void ui_event_Thermostat_setting_header_Setting_back_button( lv_event_t * e);
void ui_event_Thermostat_setting_header_Setting_accept_button( lv_event_t * e);
lv_obj_t *ui_Container1;
lv_obj_t *ui_Override_heat_container;
lv_obj_t *ui_Heat_override_setpoint;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Override_cool_container;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Cool_override_setpoint;
lv_obj_t *ui_Divider1;
lv_obj_t *ui_Schedule_buttons;
void ui_event_schedule_button( lv_event_t * e);
lv_obj_t *ui_schedule_button;
lv_obj_t *ui_Label8;
lv_obj_t *ui_ac_button_container;
void ui_event_use_ac_button( lv_event_t * e);
lv_obj_t *ui_use_ac_button;
lv_obj_t *ui_Label9;
void ui_event_stop_ac_button( lv_event_t * e);
lv_obj_t *ui_stop_ac_button;
lv_obj_t *ui_Label12;
void ui_event_allow_ac_button( lv_event_t * e);
lv_obj_t *ui_allow_ac_button;
lv_obj_t *ui_Label22;
lv_obj_t *ui_power_button_container;
void ui_event_off_button( lv_event_t * e);
lv_obj_t *ui_off_button;
lv_obj_t *ui_Label7;
void ui_event_on_button( lv_event_t * e);
lv_obj_t *ui_on_button;
lv_obj_t *ui_Label10;


// SCREEN: ui_CO2
void ui_CO2_screen_init(void);
void ui_event_CO2( lv_event_t * e);
lv_obj_t *ui_CO2;
lv_obj_t *ui_Thermostat_setting_header1;
void ui_event_Thermostat_setting_header1_Setting_back_button( lv_event_t * e);
void ui_event_Thermostat_setting_header1_Setting_accept_button( lv_event_t * e);
lv_obj_t *ui_Container2;
lv_obj_t *ui_Override_speed_container1;
lv_obj_t *ui_co2_target;
lv_obj_t *ui_Container11;
lv_obj_t *ui_co2_symbol1;
lv_obj_t *ui_Label11;


// SCREEN: ui_Schedule
void ui_Schedule_screen_init(void);
void ui_event_Schedule( lv_event_t * e);
lv_obj_t *ui_Schedule;
lv_obj_t *ui_Schedule_header;
void ui_event_Schedule_header_Setting_back_button( lv_event_t * e);
void ui_event_Schedule_header_Setting_accept_button( lv_event_t * e);
lv_obj_t *ui_Container14;
lv_obj_t *ui_TabView1;
lv_obj_t *ui_DAY;
lv_obj_t *ui_Day_heat_container;
lv_obj_t *ui_Day_heat_setpoint;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Day_cool_container;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Day_cool_setpoint;
lv_obj_t *ui_Divider2;
lv_obj_t *ui_Day_time_container;
lv_obj_t *ui_Day_hrs_container;
lv_obj_t *ui_Day_hr;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Day_min_container;
lv_obj_t *ui_Day_min;
lv_obj_t *ui_Label17;
lv_obj_t *ui_NIGHT;
lv_obj_t *ui_Night_heat_container;
lv_obj_t *ui_Night_heat_setpoint;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Night_cool_container;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Night_cool_setpoint;
lv_obj_t *ui_Divider3;
lv_obj_t *ui_Night_time_container;
lv_obj_t *ui_Night_hrs_container;
lv_obj_t *ui_Night_hr;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Night_min_container;
lv_obj_t *ui_Night_min;
lv_obj_t *ui_Label20;


// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
lv_obj_t *ui_Settings;
lv_obj_t *ui_Setting_header1;
void ui_event_Setting_header1_Setting_back_button( lv_event_t * e);
lv_obj_t *ui_Container3;
lv_obj_t *ui_Settings_buttons_left;
void ui_event_equipment_button( lv_event_t * e);
lv_obj_t *ui_equipment_button;
lv_obj_t *ui_Label25;
void ui_event_temp_limit_button( lv_event_t * e);
lv_obj_t *ui_temp_limit_button;
lv_obj_t *ui_Label26;
void ui_event_equipment_button2( lv_event_t * e);
lv_obj_t *ui_equipment_button2;
lv_obj_t *ui_Label27;
lv_obj_t *ui_Divider4;
lv_obj_t *ui_Settings_buttons_right;
void ui_event_schedule_button2( lv_event_t * e);
lv_obj_t *ui_schedule_button2;
lv_obj_t *ui_Label23;


// SCREEN: ui_Equipment
void ui_Equipment_screen_init(void);
void ui_event_Equipment( lv_event_t * e);
lv_obj_t *ui_Equipment;
lv_obj_t *ui_Setting_header2;
void ui_event_Setting_header2_Setting_back_button( lv_event_t * e);
void ui_event_Setting_header2_Setting_accept_button( lv_event_t * e);
lv_obj_t *ui_Container4;
lv_obj_t *ui_controller_type_container;
lv_obj_t *ui_Label35;
void ui_event_controller_type( lv_event_t * e);
lv_obj_t *ui_controller_type;
lv_obj_t *ui_heat_type_container;
lv_obj_t *ui_Label36;
lv_obj_t *ui_heat_type;
lv_obj_t *ui_cool_type_container;
lv_obj_t *ui_Label37;
lv_obj_t *ui_cool_type;
lv_obj_t *ui_makeup_air_container;
lv_obj_t *ui_Label38;
lv_obj_t *ui_makeup_air_switch;


// SCREEN: ui_Temp_limits
void ui_Temp_limits_screen_init(void);
void ui_event_Temp_limits( lv_event_t * e);
lv_obj_t *ui_Temp_limits;
lv_obj_t *ui_Thermostat_setting_header2;
void ui_event_Thermostat_setting_header2_Setting_back_button( lv_event_t * e);
void ui_event_Thermostat_setting_header2_Setting_accept_button( lv_event_t * e);
lv_obj_t *ui_Container5;
lv_obj_t *ui_heat_limit_container;
lv_obj_t *ui_heat_limit;
lv_obj_t *ui_Label28;
lv_obj_t *ui_Divider5;
lv_obj_t *ui_Override_cool_container1;
lv_obj_t *ui_cool_limit;
lv_obj_t *ui_Label29;


// SCREEN: ui_Temp_offsets
void ui_Temp_offsets_screen_init(void);
void ui_event_Temp_offsets( lv_event_t * e);
lv_obj_t *ui_Temp_offsets;
lv_obj_t *ui_Thermostat_setting_header3;
void ui_event_Thermostat_setting_header3_Setting_back_button( lv_event_t * e);
void ui_event_Thermostat_setting_header3_Setting_accept_button( lv_event_t * e);
lv_obj_t *ui_Container7;
lv_obj_t *ui_indoor_offset_container;
lv_obj_t *ui_Label30;
void ui_event_indoor_offset( lv_event_t * e);
lv_obj_t *ui_indoor_offset;
lv_obj_t *ui_indoor_offset_label;
lv_obj_t *ui_fan_offset_divider;
lv_obj_t *ui_fan_offset_container;
lv_obj_t *ui_Label39;
void ui_event_fan_offset( lv_event_t * e);
lv_obj_t *ui_fan_offset;
lv_obj_t *ui_fan_offset_label;


// SCREEN: ui_Wifi
void ui_Wifi_screen_init(void);
void ui_event_Wifi( lv_event_t * e);
lv_obj_t *ui_Wifi;
lv_obj_t *ui_Setting_header3;
void ui_event_Setting_header3_Setting_back_button( lv_event_t * e);
void ui_event_Setting_header3_Setting_accept_button( lv_event_t * e);
lv_obj_t *ui_Container8;
lv_obj_t *ui_ssid_container;
lv_obj_t *ui_Label40;
lv_obj_t *ui_wifi_ssid;
lv_obj_t *ui_password_container;
lv_obj_t *ui_Label41;
lv_obj_t *ui_wifi_password;
lv_obj_t *ui_log_name_container;
lv_obj_t *ui_Label42;
lv_obj_t *ui_log_name;
lv_obj_t *ui_wifi_keyboard;


// SCREEN: ui_Restart
void ui_Restart_screen_init(void);
lv_obj_t *ui_Restart;
lv_obj_t *ui_boot_message1;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Load_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 2000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Home( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      on_home_load_start( e );
}
if ( event_code == LV_EVENT_SCREEN_UNLOAD_START) {
      on_home_unload_start( e );
}
}
void ui_event_Fan( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Fan_speed_override, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Fan_speed_override_screen_init);
}
}
void ui_event_settings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
}
}
void ui_event_indoor_temps_container( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Thermostat, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Thermostat_screen_init);
}
}
void ui_event_co2_container( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_CO2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_CO2_screen_init);
}
}
void ui_event_fan_setting_header_Setting_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
}
}
void ui_event_fan_setting_header_Setting_accept_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
      set_fan_override( e );
}
}
void ui_event_Thermostat( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      thermostat_load_start( e );
}
}
void ui_event_Thermostat_setting_header_Setting_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
}
}
void ui_event_Thermostat_setting_header_Setting_accept_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_thermostat_override( e );
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
}
}
void ui_event_schedule_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Schedule, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Schedule_screen_init);
}
}
void ui_event_use_ac_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_use_ac( e );
}
}
void ui_event_stop_ac_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_stop_ac( e );
}
}
void ui_event_allow_ac_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_allow_ac( e );
}
}
void ui_event_off_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_system_off( e );
}
}
void ui_event_on_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_system_on( e );
}
}
void ui_event_CO2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      co2_load_start( e );
}
}
void ui_event_Thermostat_setting_header1_Setting_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
}
}
void ui_event_Thermostat_setting_header1_Setting_accept_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_target_co2( e );
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
}
}
void ui_event_Schedule( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      schedule_load_start( e );
}
}
void ui_event_Schedule_header_Setting_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Thermostat, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Thermostat_screen_init);
}
}
void ui_event_Schedule_header_Setting_accept_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_schedule( e );
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
}
}
void ui_event_Setting_header1_Setting_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
}
}
void ui_event_equipment_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Equipment, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Equipment_screen_init);
}
}
void ui_event_temp_limit_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Temp_limits, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Temp_limits_screen_init);
}
}
void ui_event_equipment_button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Temp_offsets, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Temp_offsets_screen_init);
}
}
void ui_event_schedule_button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Wifi, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Wifi_screen_init);
}
}
void ui_event_Equipment( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      equipment_settings_load_start( e );
}
}
void ui_event_Setting_header2_Setting_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
}
}
void ui_event_Setting_header2_Setting_accept_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      save_equipment_settings( e );
}
}
void ui_event_controller_type( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      controller_type_selection_changed( e );
}
}
void ui_event_Temp_limits( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      temp_limits_load_start( e );
}
}
void ui_event_Thermostat_setting_header2_Setting_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
}
}
void ui_event_Thermostat_setting_header2_Setting_accept_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      save_temp_limits( e );
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
}
}
void ui_event_Temp_offsets( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      temp_offsets_load_start( e );
}
}
void ui_event_Thermostat_setting_header3_Setting_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
}
}
void ui_event_Thermostat_setting_header3_Setting_accept_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      save_temp_offsets( e );
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
}
}
void ui_event_indoor_offset( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      temp_offset_changed( e );
}
}
void ui_event_fan_offset( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      temp_offset_changed( e );
}
}
void ui_event_Wifi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      wifi_settings_load_start( e );
}
}
void ui_event_Setting_header3_Setting_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings_screen_init);
}
}
void ui_event_Setting_header3_Setting_accept_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
      save_wifi_settings( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Boot_screen_init();
ui_Home_screen_init();
ui_Fan_speed_override_screen_init();
ui_Thermostat_screen_init();
ui_CO2_screen_init();
ui_Schedule_screen_init();
ui_Settings_screen_init();
ui_Equipment_screen_init();
ui_Temp_limits_screen_init();
ui_Temp_offsets_screen_init();
ui_Wifi_screen_init();
ui_Restart_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Boot);
}
