// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_home_load_start(lv_event_t * e);
void on_home_unload_start(lv_event_t * e);
void set_fan_override(lv_event_t * e);
void thermostat_load_start(lv_event_t * e);
void set_thermostat_override(lv_event_t * e);
void set_use_ac(lv_event_t * e);
void set_stop_ac(lv_event_t * e);
void set_allow_ac(lv_event_t * e);
void set_system_off(lv_event_t * e);
void set_system_on(lv_event_t * e);
void co2_load_start(lv_event_t * e);
void set_target_co2(lv_event_t * e);
void schedule_load_start(lv_event_t * e);
void set_schedule(lv_event_t * e);
void equipment_settings_load_start(lv_event_t * e);
void save_equipment_settings(lv_event_t * e);
void controller_type_selection_changed(lv_event_t * e);
void temp_limits_load_start(lv_event_t * e);
void save_temp_limits(lv_event_t * e);
void temp_offsets_load_start(lv_event_t * e);
void save_temp_offsets(lv_event_t * e);
void temp_offset_changed(lv_event_t * e);
void wifi_settings_load_start(lv_event_t * e);
void save_wifi_settings(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
