// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui

#include "UIManager.h"
#include "ui.h"

void set_fan_override(lv_event_t *e) { UIManager::eventsInst()->eFanOverride(); }

void set_thermostat_override(lv_event_t *e) { UIManager::eventsInst()->eThermotatOverride(); }

void set_use_ac(lv_event_t *e) { UIManager::eventsInst()->eUseAC(); }

void set_stop_ac(lv_event_t *e) { UIManager::eventsInst()->eStopAC(); }

void set_allow_ac(lv_event_t *e) { UIManager::eventsInst()->eAllowAC(); }

void set_system_off(lv_event_t *e) { UIManager::eventsInst()->eSystemOff(); }

void set_system_on(lv_event_t *e) { UIManager::eventsInst()->eSystemOn(); }

void set_target_co2(lv_event_t *e) { UIManager::eventsInst()->eTargetCO2(); }

void set_schedule(lv_event_t *e) { UIManager::eventsInst()->eSchedule(); }

void on_home_load_start(lv_event_t *e) { UIManager::eventsInst()->eHomeLoadStart(); }

void on_home_unload_start(lv_event_t *e) { UIManager::eventsInst()->eHomeUnloadStart(); }

void co2_load_start(lv_event_t *e) { UIManager::eventsInst()->eCO2LoadStart(); }

void thermostat_load_start(lv_event_t *e) { UIManager::eventsInst()->eThermostatLoadStart(); }

void schedule_load_start(lv_event_t *e) { UIManager::eventsInst()->eScheduleLoadStart(); }

void save_equipment_settings(lv_event_t *e) { UIManager::eventsInst()->eSaveEquipmentSettings(); }

void save_temp_limits(lv_event_t *e) { UIManager::eventsInst()->eSaveTempLimits(); }

void save_temp_offsets(lv_event_t *e) { UIManager::eventsInst()->eSaveTempOffsets(); }

void save_wifi_settings(lv_event_t *e) { UIManager::eventsInst()->eSaveWifiSettings(); }

void equipment_settings_load_start(lv_event_t *e) {
    UIManager::eventsInst()->eEquipmentSettingsLoadStart();
}

void temp_limits_load_start(lv_event_t *e) { UIManager::eventsInst()->eTempLimitsLoadStart(); }

void temp_offsets_load_start(lv_event_t *e) { UIManager::eventsInst()->eTempOffsetsLoadStart(); }

void wifi_settings_load_start(lv_event_t *e) { UIManager::eventsInst()->eWifiSettingsLoadStart(); }

void temp_offset_changed(lv_event_t *e) { UIManager::eventsInst()->eTempOffsetChanged(); }

void controller_type_selection_changed(lv_event_t *e) {
    UIManager::eventsInst()->eControllerTypeSelectionChanged();
}
