// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void set_fan_override(lv_event_t * e);
void set_thermostat_override(lv_event_t * e);
void set_use_ac(lv_event_t * e);
void set_stop_ac(lv_event_t * e);
void set_allow_ac(lv_event_t * e);
void set_system_off(lv_event_t * e);
void set_system_on(lv_event_t * e);
void set_target_co2(lv_event_t * e);
void set_schedule(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
