// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: zone_controller_ui

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_test_mode_header;
lv_obj_t *ui_heat_pump_state1;
lv_obj_t *ui_normal_mode_header;
lv_obj_t *ui_heat_pump_symbol;
lv_obj_t *ui_heat_pump_state;
void ui_event_Label6( lv_event_t * e);
lv_obj_t *ui_Label6;
lv_obj_t *ui_zones_container;
lv_obj_t *ui_Label1;
lv_obj_t *ui_zone_container_1;
lv_obj_t *ui_zone_label_1;
lv_obj_t *ui_tstat_state_1;
lv_obj_t *ui_vlv_state_1;
lv_obj_t *ui_zone_container_2;
lv_obj_t *ui_zone_label_2;
lv_obj_t *ui_tstat_state_2;
lv_obj_t *ui_vlv_state_2;
lv_obj_t *ui_zone_container_3;
lv_obj_t *ui_zone_label_3;
lv_obj_t *ui_tstat_state_3;
lv_obj_t *ui_vlv_state_3;
lv_obj_t *ui_zone_container_4;
lv_obj_t *ui_zone_label_4;
lv_obj_t *ui_tstat_state_8;
lv_obj_t *ui_vlv_state_4;
lv_obj_t *ui_zone_pump_container;
lv_obj_t *ui_zone_pump_label;
lv_obj_t *ui_zone_pump_state;
lv_obj_t *ui_fancoils_container;
lv_obj_t *ui_Label2;
lv_obj_t *ui_fc_container_1;
lv_obj_t *ui_fc_label_1;
lv_obj_t *ui_fc_state_1;
lv_obj_t *ui_fc_container_2;
lv_obj_t *ui_fc_label_2;
lv_obj_t *ui_fc_state_2;
lv_obj_t *ui_fc_container_3;
lv_obj_t *ui_fc_label_3;
lv_obj_t *ui_fc_state_3;
lv_obj_t *ui_fc_container_4;
lv_obj_t *ui_fc_label_4;
lv_obj_t *ui_fc_state_4;
lv_obj_t *ui_fc_pump_container;
lv_obj_t *ui_zone_label_8;
lv_obj_t *ui_vlv_state_8;
lv_obj_t *ui_normal_mode_footer;
lv_obj_t *ui_test_mode_footer;
void ui_event_exit_test_mode_button( lv_event_t * e);
lv_obj_t *ui_exit_test_mode_button;
lv_obj_t *ui_Label7;
void ui_event_control_overlay( lv_event_t * e);
lv_obj_t *ui_control_overlay;
lv_obj_t *ui_Container9;
void ui_event_test_mode_button( lv_event_t * e);
lv_obj_t *ui_test_mode_button;
lv_obj_t *ui_Label3;
lv_obj_t *ui_system_power_container;
lv_obj_t *ui_system_off_button;
lv_obj_t *ui_Label4;
lv_obj_t *ui_system_on_button;
lv_obj_t *ui_Label5;
lv_obj_t *ui_end_lockout_button;
lv_obj_t *ui_end_lockout_label;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Label6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_control_overlay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_exit_test_mode_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_test_mode_header, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_test_mode_footer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_normal_mode_header, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_normal_mode_footer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_control_overlay( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_control_overlay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_test_mode_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_normal_mode_footer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
