// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: zone_controller_ui

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BORDER 0
#define UI_THEME_COLOR_HEAT 1
#define UI_THEME_COLOR_COOL 2
#define UI_THEME_COLOR_BUTTON_BG 3

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_border[1];
extern const ui_theme_variable_t _ui_theme_alpha_border[1];

extern const ui_theme_variable_t _ui_theme_color_heat[1];
extern const ui_theme_variable_t _ui_theme_alpha_heat[1];

extern const ui_theme_variable_t _ui_theme_color_cool[1];
extern const ui_theme_variable_t _ui_theme_alpha_cool[1];

extern const ui_theme_variable_t _ui_theme_color_button_bg[1];
extern const ui_theme_variable_t _ui_theme_alpha_button_bg[1];

extern const uint32_t* ui_theme_colors[1];
extern const uint8_t* ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
