// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: zone_controller_ui

#include "../ui.h"

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Home, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Home, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Home, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Home, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_test_mode_header = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_test_mode_header);
lv_obj_set_height( ui_test_mode_header, 44);
lv_obj_set_width( ui_test_mode_header, lv_pct(100));
lv_obj_set_align( ui_test_mode_header, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_test_mode_header, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_test_mode_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_test_mode_header, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_test_mode_header, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_side(ui_test_mode_header, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_test_mode_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_test_mode_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_test_mode_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_test_mode_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heat_pump_state1 = lv_label_create(ui_test_mode_header);
lv_obj_set_width( ui_heat_pump_state1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_heat_pump_state1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_heat_pump_state1, LV_ALIGN_CENTER );
lv_label_set_text(ui_heat_pump_state1,"TAP ZONES/PUMPS TO TOGGLE");
lv_obj_set_style_text_font(ui_heat_pump_state1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_normal_mode_header = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_normal_mode_header);
lv_obj_set_height( ui_normal_mode_header, 44);
lv_obj_set_width( ui_normal_mode_header, lv_pct(100));
lv_obj_set_align( ui_normal_mode_header, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_normal_mode_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_normal_mode_header, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_normal_mode_header, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_side(ui_normal_mode_header, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_normal_mode_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_normal_mode_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_normal_mode_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_normal_mode_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heat_pump_symbol = lv_label_create(ui_normal_mode_header);
lv_obj_set_width( ui_heat_pump_symbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_heat_pump_symbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_heat_pump_symbol, 5 );
lv_obj_set_y( ui_heat_pump_symbol, 0 );
lv_obj_set_align( ui_heat_pump_symbol, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_heat_pump_symbol,"");
lv_obj_set_style_text_font(ui_heat_pump_symbol, &ui_font_MaterialSymbols24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_heat_pump_symbol, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_heat_pump_symbol, lv_color_hex(0xF0F0F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_heat_pump_symbol, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_heat_pump_symbol, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_heat_pump_symbol, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_heat_pump_symbol, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_heat_pump_symbol, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_heat_pump_symbol, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heat_pump_state = lv_label_create(ui_normal_mode_header);
lv_obj_set_width( ui_heat_pump_state, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_heat_pump_state, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_heat_pump_state, 45 );
lv_obj_set_y( ui_heat_pump_state, 0 );
lv_obj_set_align( ui_heat_pump_state, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_heat_pump_state,"STANDBY");
lv_obj_set_style_text_font(ui_heat_pump_state, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_normal_mode_header);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label6,"");
lv_obj_add_flag( ui_Label6, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_font(ui_Label6, &ui_font_MaterialSymbols24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_zones_container = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_zones_container);
lv_obj_set_width( ui_zones_container, 167);
lv_obj_set_height( ui_zones_container, 152);
lv_obj_set_x( ui_zones_container, 0 );
lv_obj_set_y( ui_zones_container, 45 );
lv_obj_set_flex_flow(ui_zones_container,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_zones_container, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_zones_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_zones_container, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_zones_container, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_zones_container, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_zones_container, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_zones_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zones_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zones_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zones_container, -1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_zones_container);
lv_obj_set_height( ui_Label1, 25);
lv_obj_set_width( ui_Label1, lv_pct(100));
lv_obj_set_x( ui_Label1, 0 );
lv_obj_set_y( ui_Label1, -4 );
lv_label_set_text(ui_Label1,"ZONES");
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_Label1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Label1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_zone_container_1 = lv_obj_create(ui_zones_container);
lv_obj_remove_style_all(ui_zone_container_1);
lv_obj_set_height( ui_zone_container_1, 25);
lv_obj_set_width( ui_zone_container_1, lv_pct(100));
lv_obj_set_align( ui_zone_container_1, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_zone_container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_zone_container_1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_zone_container_1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_zone_container_1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_zone_container_1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_zone_container_1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zone_container_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zone_container_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zone_container_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_zone_container_1, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_COLOR, _ui_theme_color_button_bg);
ui_object_set_themeable_style_property(ui_zone_container_1, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_OPA, _ui_theme_alpha_button_bg);

lv_obj_set_style_pad_left(ui_zone_container_1, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zone_container_1, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zone_container_1, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zone_container_1, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_zone_label_1 = lv_label_create(ui_zone_container_1);
lv_obj_set_width( ui_zone_label_1, 35);
lv_obj_set_height( ui_zone_label_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_zone_label_1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_zone_label_1,"1F E");
lv_obj_set_style_text_align(ui_zone_label_1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_zone_label_1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tstat_state_1 = lv_label_create(ui_zone_container_1);
lv_obj_set_width( ui_tstat_state_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tstat_state_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tstat_state_1, 40 );
lv_obj_set_y( ui_tstat_state_1, 0 );
lv_obj_set_align( ui_tstat_state_1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_tstat_state_1,"");
ui_object_set_themeable_style_property(ui_tstat_state_1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_heat);
ui_object_set_themeable_style_property(ui_tstat_state_1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_heat);
lv_obj_set_style_text_font(ui_tstat_state_1, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_vlv_state_1 = lv_label_create(ui_zone_container_1);
lv_obj_set_width( ui_vlv_state_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_vlv_state_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_vlv_state_1, 65 );
lv_obj_set_y( ui_vlv_state_1, 0 );
lv_obj_set_align( ui_vlv_state_1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_vlv_state_1,"CLOSED");
lv_obj_set_style_text_font(ui_vlv_state_1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_vlv_state_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_vlv_state_1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_vlv_state_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_vlv_state_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_zone_container_2 = lv_obj_create(ui_zones_container);
lv_obj_remove_style_all(ui_zone_container_2);
lv_obj_set_height( ui_zone_container_2, 25);
lv_obj_set_width( ui_zone_container_2, lv_pct(100));
lv_obj_set_align( ui_zone_container_2, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_zone_container_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_zone_container_2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_zone_container_2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_zone_container_2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_zone_container_2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_zone_container_2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zone_container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zone_container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zone_container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_zone_container_2, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_COLOR, _ui_theme_color_button_bg);
ui_object_set_themeable_style_property(ui_zone_container_2, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_OPA, _ui_theme_alpha_button_bg);

lv_obj_set_style_pad_left(ui_zone_container_2, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zone_container_2, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zone_container_2, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zone_container_2, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_zone_label_2 = lv_label_create(ui_zone_container_2);
lv_obj_set_width( ui_zone_label_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_zone_label_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_zone_label_2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_zone_label_2,"1F E");
lv_obj_set_style_text_font(ui_zone_label_2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tstat_state_2 = lv_label_create(ui_zone_container_2);
lv_obj_set_width( ui_tstat_state_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tstat_state_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tstat_state_2, 40 );
lv_obj_set_y( ui_tstat_state_2, 0 );
lv_obj_set_align( ui_tstat_state_2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_tstat_state_2,"");
ui_object_set_themeable_style_property(ui_tstat_state_2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_heat);
ui_object_set_themeable_style_property(ui_tstat_state_2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_heat);
lv_obj_set_style_text_font(ui_tstat_state_2, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_vlv_state_2 = lv_label_create(ui_zone_container_2);
lv_obj_set_width( ui_vlv_state_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_vlv_state_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_vlv_state_2, 65 );
lv_obj_set_y( ui_vlv_state_2, 0 );
lv_obj_set_align( ui_vlv_state_2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_vlv_state_2,"OPENING");
lv_obj_set_style_text_font(ui_vlv_state_2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_vlv_state_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_vlv_state_2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_vlv_state_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_vlv_state_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_zone_container_3 = lv_obj_create(ui_zones_container);
lv_obj_remove_style_all(ui_zone_container_3);
lv_obj_set_height( ui_zone_container_3, 25);
lv_obj_set_width( ui_zone_container_3, lv_pct(100));
lv_obj_set_align( ui_zone_container_3, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_zone_container_3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_zone_container_3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_zone_container_3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_zone_container_3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_zone_container_3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_zone_container_3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zone_container_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zone_container_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zone_container_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_zone_container_3, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_COLOR, _ui_theme_color_button_bg);
ui_object_set_themeable_style_property(ui_zone_container_3, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_OPA, _ui_theme_alpha_button_bg);

lv_obj_set_style_pad_left(ui_zone_container_3, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zone_container_3, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zone_container_3, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zone_container_3, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_zone_label_3 = lv_label_create(ui_zone_container_3);
lv_obj_set_width( ui_zone_label_3, 35);
lv_obj_set_height( ui_zone_label_3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_zone_label_3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_zone_label_3,"2F");
lv_obj_set_style_text_align(ui_zone_label_3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_zone_label_3, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tstat_state_3 = lv_label_create(ui_zone_container_3);
lv_obj_set_width( ui_tstat_state_3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tstat_state_3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tstat_state_3, 40 );
lv_obj_set_y( ui_tstat_state_3, 0 );
lv_obj_set_align( ui_tstat_state_3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_tstat_state_3,"");
ui_object_set_themeable_style_property(ui_tstat_state_3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_heat);
ui_object_set_themeable_style_property(ui_tstat_state_3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_heat);
lv_obj_set_style_text_font(ui_tstat_state_3, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_vlv_state_3 = lv_label_create(ui_zone_container_3);
lv_obj_set_width( ui_vlv_state_3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_vlv_state_3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_vlv_state_3, 65 );
lv_obj_set_y( ui_vlv_state_3, 0 );
lv_obj_set_align( ui_vlv_state_3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_vlv_state_3,"OPEN");
lv_obj_set_style_text_font(ui_vlv_state_3, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_vlv_state_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_vlv_state_3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_vlv_state_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_vlv_state_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_zone_container_4 = lv_obj_create(ui_zones_container);
lv_obj_remove_style_all(ui_zone_container_4);
lv_obj_set_height( ui_zone_container_4, 25);
lv_obj_set_width( ui_zone_container_4, lv_pct(100));
lv_obj_set_align( ui_zone_container_4, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_zone_container_4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_zone_container_4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_zone_container_4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_zone_container_4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_zone_container_4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_zone_container_4, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zone_container_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zone_container_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zone_container_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_zone_container_4, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_COLOR, _ui_theme_color_button_bg);
ui_object_set_themeable_style_property(ui_zone_container_4, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_OPA, _ui_theme_alpha_button_bg);

lv_obj_set_style_pad_left(ui_zone_container_4, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zone_container_4, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zone_container_4, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zone_container_4, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_zone_label_4 = lv_label_create(ui_zone_container_4);
lv_obj_set_width( ui_zone_label_4, 35);
lv_obj_set_height( ui_zone_label_4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_zone_label_4, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_zone_label_4,"N/A");
lv_obj_set_style_text_align(ui_zone_label_4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_zone_label_4, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tstat_state_4 = lv_label_create(ui_zone_container_4);
lv_obj_set_width( ui_tstat_state_4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tstat_state_4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tstat_state_4, 40 );
lv_obj_set_y( ui_tstat_state_4, 0 );
lv_obj_set_align( ui_tstat_state_4, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_tstat_state_4,"");
lv_obj_add_flag( ui_tstat_state_4, LV_OBJ_FLAG_HIDDEN );   /// Flags
ui_object_set_themeable_style_property(ui_tstat_state_4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_heat);
ui_object_set_themeable_style_property(ui_tstat_state_4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_heat);
lv_obj_set_style_text_font(ui_tstat_state_4, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_vlv_state_4 = lv_label_create(ui_zone_container_4);
lv_obj_set_width( ui_vlv_state_4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_vlv_state_4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_vlv_state_4, 65 );
lv_obj_set_y( ui_vlv_state_4, 0 );
lv_obj_set_align( ui_vlv_state_4, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_vlv_state_4,"OPEN");
lv_obj_set_style_text_font(ui_vlv_state_4, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_vlv_state_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_vlv_state_4, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_vlv_state_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_vlv_state_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_zone_pump_container = lv_obj_create(ui_zones_container);
lv_obj_remove_style_all(ui_zone_pump_container);
lv_obj_set_height( ui_zone_pump_container, 25);
lv_obj_set_width( ui_zone_pump_container, lv_pct(100));
lv_obj_set_align( ui_zone_pump_container, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_zone_pump_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_zone_pump_container, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zone_pump_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zone_pump_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zone_pump_container, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_zone_pump_container, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_COLOR, _ui_theme_color_button_bg);
ui_object_set_themeable_style_property(ui_zone_pump_container, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_OPA, _ui_theme_alpha_button_bg);

lv_obj_set_style_pad_left(ui_zone_pump_container, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zone_pump_container, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zone_pump_container, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zone_pump_container, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_zone_pump_label = lv_label_create(ui_zone_pump_container);
lv_obj_set_width( ui_zone_pump_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_zone_pump_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_zone_pump_label, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_zone_pump_label,"PUMP");
lv_obj_set_style_text_font(ui_zone_pump_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_zone_pump_state = lv_label_create(ui_zone_pump_container);
lv_obj_set_width( ui_zone_pump_state, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_zone_pump_state, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_zone_pump_state, 65 );
lv_obj_set_y( ui_zone_pump_state, 0 );
lv_obj_set_align( ui_zone_pump_state, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_zone_pump_state,"ON");
lv_obj_set_style_text_font(ui_zone_pump_state, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_zone_pump_state, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_zone_pump_state, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_zone_pump_state, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_zone_pump_state, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fancoils_container = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_fancoils_container);
lv_obj_set_width( ui_fancoils_container, 132);
lv_obj_set_height( ui_fancoils_container, 152);
lv_obj_set_x( ui_fancoils_container, 0 );
lv_obj_set_y( ui_fancoils_container, 45 );
lv_obj_set_align( ui_fancoils_container, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_fancoils_container,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_fancoils_container, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_fancoils_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_fancoils_container, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_fancoils_container, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_fancoils_container, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_fancoils_container, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_fancoils_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fancoils_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fancoils_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fancoils_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_fancoils_container);
lv_obj_set_height( ui_Label2, 25);
lv_obj_set_width( ui_Label2, lv_pct(100));
lv_obj_set_x( ui_Label2, 0 );
lv_obj_set_y( ui_Label2, -4 );
lv_label_set_text(ui_Label2,"FANCOILS");
lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_Label2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Label2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fc_container_1 = lv_obj_create(ui_fancoils_container);
lv_obj_remove_style_all(ui_fc_container_1);
lv_obj_set_height( ui_fc_container_1, 25);
lv_obj_set_width( ui_fc_container_1, lv_pct(100));
lv_obj_set_x( ui_fc_container_1, 1 );
lv_obj_set_y( ui_fc_container_1, 0 );
lv_obj_set_align( ui_fc_container_1, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_fc_container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_fc_container_1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_fc_container_1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_fc_container_1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_fc_container_1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_fc_container_1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fc_container_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fc_container_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fc_container_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_fc_container_1, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fc_container_1, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fc_container_1, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fc_container_1, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_fc_label_1 = lv_label_create(ui_fc_container_1);
lv_obj_set_width( ui_fc_label_1, 60);
lv_obj_set_height( ui_fc_label_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_fc_label_1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_fc_label_1,"M BR");
lv_obj_set_style_text_align(ui_fc_label_1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_fc_label_1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fc_state_1 = lv_label_create(ui_fc_container_1);
lv_obj_set_width( ui_fc_state_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fc_state_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_fc_state_1, 70 );
lv_obj_set_y( ui_fc_state_1, 0 );
lv_obj_set_align( ui_fc_state_1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_fc_state_1,"");
ui_object_set_themeable_style_property(ui_fc_state_1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_heat);
ui_object_set_themeable_style_property(ui_fc_state_1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_heat);
lv_obj_set_style_text_font(ui_fc_state_1, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fc_container_2 = lv_obj_create(ui_fancoils_container);
lv_obj_remove_style_all(ui_fc_container_2);
lv_obj_set_height( ui_fc_container_2, 25);
lv_obj_set_width( ui_fc_container_2, lv_pct(100));
lv_obj_set_align( ui_fc_container_2, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_fc_container_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_fc_container_2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_fc_container_2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_fc_container_2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_fc_container_2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_fc_container_2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fc_container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fc_container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fc_container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_fc_container_2, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fc_container_2, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fc_container_2, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fc_container_2, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_fc_label_2 = lv_label_create(ui_fc_container_2);
lv_obj_set_width( ui_fc_label_2, 60);
lv_obj_set_height( ui_fc_label_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_fc_label_2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_fc_label_2,"N BR");
lv_obj_set_style_text_align(ui_fc_label_2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_fc_label_2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fc_state_2 = lv_label_create(ui_fc_container_2);
lv_obj_set_width( ui_fc_state_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fc_state_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_fc_state_2, 70 );
lv_obj_set_y( ui_fc_state_2, 0 );
lv_obj_set_align( ui_fc_state_2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_fc_state_2,"");
ui_object_set_themeable_style_property(ui_fc_state_2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_heat);
ui_object_set_themeable_style_property(ui_fc_state_2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_heat);
lv_obj_set_style_text_font(ui_fc_state_2, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fc_container_3 = lv_obj_create(ui_fancoils_container);
lv_obj_remove_style_all(ui_fc_container_3);
lv_obj_set_height( ui_fc_container_3, 25);
lv_obj_set_width( ui_fc_container_3, lv_pct(100));
lv_obj_set_align( ui_fc_container_3, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_fc_container_3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_fc_container_3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_fc_container_3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_fc_container_3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_fc_container_3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_fc_container_3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fc_container_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fc_container_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fc_container_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_fc_container_3, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fc_container_3, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fc_container_3, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fc_container_3, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_fc_label_3 = lv_label_create(ui_fc_container_3);
lv_obj_set_width( ui_fc_label_3, 60);
lv_obj_set_height( ui_fc_label_3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_fc_label_3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_fc_label_3,"S BR");
lv_obj_set_style_text_align(ui_fc_label_3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_fc_label_3, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fc_state_3 = lv_label_create(ui_fc_container_3);
lv_obj_set_width( ui_fc_state_3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fc_state_3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_fc_state_3, 70 );
lv_obj_set_y( ui_fc_state_3, 0 );
lv_obj_set_align( ui_fc_state_3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_fc_state_3,"");
ui_object_set_themeable_style_property(ui_fc_state_3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_heat);
ui_object_set_themeable_style_property(ui_fc_state_3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_heat);
lv_obj_set_style_text_font(ui_fc_state_3, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fc_container_4 = lv_obj_create(ui_fancoils_container);
lv_obj_remove_style_all(ui_fc_container_4);
lv_obj_set_height( ui_fc_container_4, 25);
lv_obj_set_width( ui_fc_container_4, lv_pct(100));
lv_obj_set_align( ui_fc_container_4, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_fc_container_4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_fc_container_4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_fc_container_4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_fc_container_4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_fc_container_4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_fc_container_4, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fc_container_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fc_container_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fc_container_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_fc_container_4, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fc_container_4, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fc_container_4, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fc_container_4, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_fc_label_4 = lv_label_create(ui_fc_container_4);
lv_obj_set_width( ui_fc_label_4, 60);
lv_obj_set_height( ui_fc_label_4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_fc_label_4, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_fc_label_4,"N/A");
lv_obj_set_style_text_align(ui_fc_label_4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_fc_label_4, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fc_state_4 = lv_label_create(ui_fc_container_4);
lv_obj_set_width( ui_fc_state_4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fc_state_4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_fc_state_4, 70 );
lv_obj_set_y( ui_fc_state_4, 0 );
lv_obj_set_align( ui_fc_state_4, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_fc_state_4,"");
ui_object_set_themeable_style_property(ui_fc_state_4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_heat);
ui_object_set_themeable_style_property(ui_fc_state_4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_heat);
lv_obj_set_style_text_font(ui_fc_state_4, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fc_pump_container = lv_obj_create(ui_fancoils_container);
lv_obj_remove_style_all(ui_fc_pump_container);
lv_obj_set_height( ui_fc_pump_container, 25);
lv_obj_set_width( ui_fc_pump_container, lv_pct(100));
lv_obj_set_align( ui_fc_pump_container, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_fc_pump_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_fc_pump_container, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_fc_pump_container, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_pad_left(ui_fc_pump_container, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fc_pump_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fc_pump_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fc_pump_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_fc_pump_container, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_COLOR, _ui_theme_color_button_bg);
ui_object_set_themeable_style_property(ui_fc_pump_container, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_OPA, _ui_theme_alpha_button_bg);

lv_obj_set_style_pad_left(ui_fc_pump_container, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fc_pump_container, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fc_pump_container, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fc_pump_container, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_zone_label_8 = lv_label_create(ui_fc_pump_container);
lv_obj_set_width( ui_zone_label_8, 60);
lv_obj_set_height( ui_zone_label_8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_zone_label_8, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_zone_label_8,"PUMP");
lv_obj_set_style_text_align(ui_zone_label_8, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_zone_label_8, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fc_pump_state = lv_label_create(ui_fc_pump_container);
lv_obj_set_width( ui_fc_pump_state, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fc_pump_state, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_fc_pump_state, 70 );
lv_obj_set_y( ui_fc_pump_state, 0 );
lv_obj_set_align( ui_fc_pump_state, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_fc_pump_state,"OFF");
lv_obj_set_style_text_font(ui_fc_pump_state, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_fc_pump_state, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fc_pump_state, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fc_pump_state, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fc_pump_state, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_normal_mode_footer = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_normal_mode_footer);
lv_obj_set_height( ui_normal_mode_footer, 40);
lv_obj_set_width( ui_normal_mode_footer, lv_pct(100));
lv_obj_set_align( ui_normal_mode_footer, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_normal_mode_footer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_normal_mode_footer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_normal_mode_footer, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_clear_flag( ui_normal_mode_footer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_test_mode_footer = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_test_mode_footer);
lv_obj_set_height( ui_test_mode_footer, 40);
lv_obj_set_width( ui_test_mode_footer, lv_pct(100));
lv_obj_set_align( ui_test_mode_footer, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_test_mode_footer, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_clear_flag( ui_test_mode_footer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_exit_test_mode_button = lv_btn_create(ui_test_mode_footer);
lv_obj_set_width( ui_exit_test_mode_button, 120);
lv_obj_set_height( ui_exit_test_mode_button, 25);
lv_obj_set_x( ui_exit_test_mode_button, 0 );
lv_obj_set_y( ui_exit_test_mode_button, 1 );
lv_obj_set_align( ui_exit_test_mode_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_exit_test_mode_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_exit_test_mode_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_exit_test_mode_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_button_bg);
ui_object_set_themeable_style_property(ui_exit_test_mode_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_button_bg);
ui_object_set_themeable_style_property(ui_exit_test_mode_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_exit_test_mode_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_exit_test_mode_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_exit_test_mode_button);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"EXIT TEST");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_control_overlay = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_control_overlay);
lv_obj_set_width( ui_control_overlay, lv_pct(100));
lv_obj_set_height( ui_control_overlay, lv_pct(100));
lv_obj_set_align( ui_control_overlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_control_overlay, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_control_overlay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_control_overlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_control_overlay, 180, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container9 = lv_obj_create(ui_control_overlay);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_width( ui_Container9, 160);
lv_obj_set_height( ui_Container9, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Container9, 0 );
lv_obj_set_y( ui_Container9, 30 );
lv_obj_set_align( ui_Container9, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Container9,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container9, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container9, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container9, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container9, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Container9, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container9, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_test_mode_button = lv_btn_create(ui_Container9);
lv_obj_set_height( ui_test_mode_button, 40);
lv_obj_set_width( ui_test_mode_button, lv_pct(100));
lv_obj_set_align( ui_test_mode_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_test_mode_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_test_mode_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_test_mode_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_button_bg);
ui_object_set_themeable_style_property(ui_test_mode_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_button_bg);
ui_object_set_themeable_style_property(ui_test_mode_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_test_mode_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_test_mode_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_test_mode_button);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"TEST MODE");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_system_power_container = lv_obj_create(ui_Container9);
lv_obj_remove_style_all(ui_system_power_container);
lv_obj_set_width( ui_system_power_container, lv_pct(100));
lv_obj_set_height( ui_system_power_container, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_system_power_container, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_system_power_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_system_off_button = lv_btn_create(ui_system_power_container);
lv_obj_set_height( ui_system_off_button, 40);
lv_obj_set_width( ui_system_off_button, lv_pct(100));
lv_obj_set_align( ui_system_off_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_system_off_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_system_off_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_system_off_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_button_bg);
ui_object_set_themeable_style_property(ui_system_off_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_button_bg);
ui_object_set_themeable_style_property(ui_system_off_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_system_off_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_system_off_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_system_off_button);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"SYSTEM OFF");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_system_on_button = lv_btn_create(ui_system_power_container);
lv_obj_set_height( ui_system_on_button, 40);
lv_obj_set_width( ui_system_on_button, lv_pct(100));
lv_obj_set_align( ui_system_on_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_system_on_button, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_system_on_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_system_on_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_button_bg);
ui_object_set_themeable_style_property(ui_system_on_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_button_bg);
ui_object_set_themeable_style_property(ui_system_on_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_system_on_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_system_on_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_system_on_button);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"SYSTEM ON");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_end_lockout_button = lv_btn_create(ui_Container9);
lv_obj_set_height( ui_end_lockout_button, 40);
lv_obj_set_width( ui_end_lockout_button, lv_pct(100));
lv_obj_set_align( ui_end_lockout_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_end_lockout_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_end_lockout_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_end_lockout_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_button_bg);
ui_object_set_themeable_style_property(ui_end_lockout_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_button_bg);
ui_object_set_themeable_style_property(ui_end_lockout_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_border);
ui_object_set_themeable_style_property(ui_end_lockout_button, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_border);
lv_obj_set_style_border_width(ui_end_lockout_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_end_lockout_label = lv_label_create(ui_end_lockout_button);
lv_obj_set_width( ui_end_lockout_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_end_lockout_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_end_lockout_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_end_lockout_label,"RST LOCKOUT");
lv_obj_set_style_text_font(ui_end_lockout_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Label6, ui_event_Label6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_exit_test_mode_button, ui_event_exit_test_mode_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_test_mode_button, ui_event_test_mode_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_system_off_button, ui_event_system_off_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_system_on_button, ui_event_system_on_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_control_overlay, ui_event_control_overlay, LV_EVENT_ALL, NULL);

}
