// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ui

#include "../ui.h"

void ui_Fan_speed_override_screen_init(void)
{
ui_Fan_speed_override = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Fan_speed_override, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Fan_speed_override,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Fan_speed_override, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_pad_left(ui_Fan_speed_override, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Fan_speed_override, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Fan_speed_override, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Fan_speed_override, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Fan_speed_override, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Fan_speed_override, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fan_setting_header = ui_Setting_header_create(ui_Fan_speed_override);
lv_obj_set_x( ui_fan_setting_header, 0 );
lv_obj_set_y( ui_fan_setting_header, 0 );

lv_label_set_text(ui_comp_get_child(ui_fan_setting_header, UI_COMP_SETTING_HEADER_SETTING_TITLE),"FAN OVERRIDE");





ui_fan_override_container = lv_obj_create(ui_Fan_speed_override);
lv_obj_remove_style_all(ui_fan_override_container);
lv_obj_set_width( ui_fan_override_container, 300);
lv_obj_set_height( ui_fan_override_container, 174);
lv_obj_set_x( ui_fan_override_container, 0 );
lv_obj_set_y( ui_fan_override_container, 10 );
lv_obj_set_align( ui_fan_override_container, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_fan_override_container,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_fan_override_container, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_fan_override_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Override_speed_container = lv_obj_create(ui_fan_override_container);
lv_obj_remove_style_all(ui_Override_speed_container);
lv_obj_set_height( ui_Override_speed_container, 143);
lv_obj_set_width( ui_Override_speed_container, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Override_speed_container, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Override_speed_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Fan_override_speed = lv_roller_create(ui_Override_speed_container);
lv_roller_set_options( ui_Fan_override_speed, "OFF\n10%\n20%\n30%\n40%\n50%\n60%\n70%\n80%\n90%\n100%", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Fan_override_speed, 100);
lv_obj_set_width( ui_Fan_override_speed, LV_SIZE_CONTENT);  /// 60
lv_obj_set_align( ui_Fan_override_speed, LV_ALIGN_TOP_MID );
lv_obj_set_style_text_font(ui_Fan_override_speed, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Fan_override_speed, lv_color_hex(0x44474C), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Fan_override_speed, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Override_speed_container);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label5,"SPEED");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Divider = lv_obj_create(ui_fan_override_container);
lv_obj_set_width( ui_Divider, 1);
lv_obj_set_height( ui_Divider, 100);
lv_obj_set_x( ui_Divider, 0 );
lv_obj_set_y( ui_Divider, -3 );
lv_obj_set_align( ui_Divider, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Divider, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Divider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Divider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Divider, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Divider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Divider, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Divider, LV_BORDER_SIDE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Override_time_container = lv_obj_create(ui_fan_override_container);
lv_obj_remove_style_all(ui_Override_time_container);
lv_obj_set_width( ui_Override_time_container, 135);
lv_obj_set_height( ui_Override_time_container, 143);
lv_obj_set_align( ui_Override_time_container, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Override_time_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Override_hrs_container = lv_obj_create(ui_Override_time_container);
lv_obj_remove_style_all(ui_Override_hrs_container);
lv_obj_set_height( ui_Override_hrs_container, 143);
lv_obj_set_width( ui_Override_hrs_container, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Override_hrs_container, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Override_hrs_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Fan_override_hrs = lv_roller_create(ui_Override_hrs_container);
lv_roller_set_options( ui_Fan_override_hrs, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Fan_override_hrs, 100);
lv_obj_set_width( ui_Fan_override_hrs, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Fan_override_hrs, LV_ALIGN_TOP_MID );
lv_obj_set_style_text_font(ui_Fan_override_hrs, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Fan_override_hrs, lv_color_hex(0x44474C), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Fan_override_hrs, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Override_hrs_container);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label1,"HRS");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Override_time_container);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 0 );
lv_obj_set_y( ui_Label6, -21 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,":");
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Override_mins_container = lv_obj_create(ui_Override_time_container);
lv_obj_remove_style_all(ui_Override_mins_container);
lv_obj_set_height( ui_Override_mins_container, 143);
lv_obj_set_width( ui_Override_mins_container, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Override_mins_container, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Override_mins_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Fan_override_mins = lv_roller_create(ui_Override_mins_container);
lv_roller_set_options( ui_Fan_override_mins, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Fan_override_mins, 100);
lv_obj_set_width( ui_Fan_override_mins, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Fan_override_mins, LV_ALIGN_TOP_MID );
lv_obj_set_style_text_font(ui_Fan_override_mins, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Fan_override_mins, lv_color_hex(0x44474C), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Fan_override_mins, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Override_mins_container);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label2,"MINS");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fan_override_secondary_container = lv_obj_create(ui_Fan_speed_override);
lv_obj_remove_style_all(ui_fan_override_secondary_container);
lv_obj_set_height( ui_fan_override_secondary_container, 160);
lv_obj_set_width( ui_fan_override_secondary_container, lv_pct(100));
lv_obj_set_align( ui_fan_override_secondary_container, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_fan_override_secondary_container, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_fan_override_secondary_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label21 = lv_label_create(ui_fan_override_secondary_container);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"PLEASE USE PRIMARY \nCONTROLLER TO SET \nFAN OVERRIDES");
lv_obj_set_style_text_align(ui_Label21, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_comp_get_child(ui_fan_setting_header, UI_COMP_SETTING_HEADER_SETTING_BACK_BUTTON), ui_event_fan_setting_header_Setting_back_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_comp_get_child(ui_fan_setting_header, UI_COMP_SETTING_HEADER_SETTING_ACCEPT_BUTTON), ui_event_fan_setting_header_Setting_accept_button, LV_EVENT_ALL, NULL);

}
