// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui

#include "../ui.h"

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Home, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Home, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Home, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Home, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header = lv_obj_create(ui_Home);
lv_obj_set_width( ui_Header, 300);
lv_obj_set_height( ui_Header, 35);
lv_obj_set_align( ui_Header, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Header,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Header, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Header, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Header, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Header, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Header, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Header, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Clock_container = lv_obj_create(ui_Header);
lv_obj_remove_style_all(ui_Clock_container);
lv_obj_set_width( ui_Clock_container, 67);
lv_obj_set_height( ui_Clock_container, 35);
lv_obj_set_x( ui_Clock_container, 0 );
lv_obj_set_y( ui_Clock_container, -6 );
lv_obj_set_align( ui_Clock_container, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Clock_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Clock_container, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Clock_container, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Clock_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Clock_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clock_value = lv_label_create(ui_Clock_container);
lv_obj_set_width( ui_clock_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_clock_value, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock_value,"11:88 ");
lv_obj_set_style_text_font(ui_clock_value, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Humidity = lv_obj_create(ui_Header);
lv_obj_remove_style_all(ui_Humidity);
lv_obj_set_width( ui_Humidity, 67);
lv_obj_set_height( ui_Humidity, 35);
lv_obj_set_x( ui_Humidity, 0 );
lv_obj_set_y( ui_Humidity, -6 );
lv_obj_set_align( ui_Humidity, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Humidity, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Humidity, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Humidity, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Humidity, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Humidity, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Humidity_symbol = lv_label_create(ui_Humidity);
lv_obj_set_width( ui_Humidity_symbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Humidity_symbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Humidity_symbol, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Humidity_symbol,"");
lv_obj_set_style_text_font(ui_Humidity_symbol, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Humidity_value = lv_label_create(ui_Humidity);
lv_obj_set_width( ui_Humidity_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Humidity_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Humidity_value, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Humidity_value,"66%");
lv_obj_set_style_text_font(ui_Humidity_value, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Fan = lv_obj_create(ui_Header);
lv_obj_remove_style_all(ui_Fan);
lv_obj_set_width( ui_Fan, 67);
lv_obj_set_height( ui_Fan, 35);
lv_obj_set_x( ui_Fan, 0 );
lv_obj_set_y( ui_Fan, -6 );
lv_obj_set_align( ui_Fan, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Fan,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Fan, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Fan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Fan, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Fan, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Fan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Fan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Fan_symbol = lv_label_create(ui_Fan);
lv_obj_set_width( ui_Fan_symbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Fan_symbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Fan_symbol, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Fan_symbol,"");
lv_obj_set_style_text_font(ui_Fan_symbol, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Fan_value = lv_label_create(ui_Fan);
lv_obj_set_width( ui_Fan_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Fan_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Fan_value, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Fan_value,"90%");
lv_obj_set_style_text_font(ui_Fan_value, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Fan_value, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Fan_value, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Fan_value, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Fan_value, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_out_temp = lv_obj_create(ui_Header);
lv_obj_remove_style_all(ui_out_temp);
lv_obj_set_width( ui_out_temp, 60);
lv_obj_set_height( ui_out_temp, 35);
lv_obj_set_x( ui_out_temp, 0 );
lv_obj_set_y( ui_out_temp, -6 );
lv_obj_set_align( ui_out_temp, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_out_temp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_out_temp, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_out_temp, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_out_temp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_out_temp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_out_symbol = lv_label_create(ui_out_temp);
lv_obj_set_width( ui_out_symbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_out_symbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_out_symbol, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_out_symbol,"");
lv_obj_set_style_text_font(ui_out_symbol, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Out_temp_value = lv_label_create(ui_out_temp);
lv_obj_set_width( ui_Out_temp_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Out_temp_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Out_temp_value, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Out_temp_value,"77°");
lv_obj_set_style_text_font(ui_Out_temp_value, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settings = lv_obj_create(ui_Header);
lv_obj_remove_style_all(ui_settings);
lv_obj_set_width( ui_settings, 35);
lv_obj_set_height( ui_settings, 35);
lv_obj_set_x( ui_settings, 0 );
lv_obj_set_y( ui_settings, -6 );
lv_obj_set_align( ui_settings, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_settings, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_settings, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_settings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_settings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settings_symbol = lv_label_create(ui_settings);
lv_obj_set_width( ui_settings_symbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settings_symbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_settings_symbol, LV_ALIGN_CENTER );
lv_label_set_text(ui_settings_symbol,"");
lv_obj_set_style_text_font(ui_settings_symbol, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Footer = lv_obj_create(ui_Home);
lv_obj_set_width( ui_Footer, 300);
lv_obj_set_height( ui_Footer, 40);
lv_obj_set_align( ui_Footer, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_Footer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Footer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_Footer, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_set_style_bg_color(ui_Footer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Footer, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Footer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Footer, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Footer, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Footer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_message_container = lv_obj_create(ui_Footer);
lv_obj_remove_style_all(ui_message_container);
lv_obj_set_width( ui_message_container, lv_pct(100));
lv_obj_set_height( ui_message_container, lv_pct(100));
lv_obj_set_align( ui_message_container, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_message_container,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_message_container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_message_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_message_close = lv_label_create(ui_message_container);
lv_obj_set_width( ui_message_close, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_message_close, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_message_close, LV_ALIGN_CENTER );
lv_label_set_text(ui_message_close,"");
lv_obj_set_style_text_font(ui_message_close, &ui_font_MaterialSymbols24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_message_close, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_message_close, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_message_close, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_message_close, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_message_text = lv_label_create(ui_message_container);
lv_obj_set_width( ui_message_text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_message_text, LV_SIZE_CONTENT);   /// 100
lv_obj_set_align( ui_message_text, LV_ALIGN_CENTER );
lv_label_set_text(ui_message_text,"MESSAGE");

ui_Indoor_Temp = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_Indoor_Temp);
lv_obj_set_width( ui_Indoor_Temp, 118);
lv_obj_set_height( ui_Indoor_Temp, 140);
lv_obj_set_x( ui_Indoor_Temp, 10 );
lv_obj_set_y( ui_Indoor_Temp, 0 );
lv_obj_set_align( ui_Indoor_Temp, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Indoor_Temp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_indoor_temps_container = lv_obj_create(ui_Indoor_Temp);
lv_obj_remove_style_all(ui_indoor_temps_container);
lv_obj_set_height( ui_indoor_temps_container, 108);
lv_obj_set_width( ui_indoor_temps_container, lv_pct(100));
lv_obj_set_align( ui_indoor_temps_container, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_indoor_temps_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Indoor_temp_value = lv_label_create(ui_indoor_temps_container);
lv_obj_set_width( ui_Indoor_temp_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Indoor_temp_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Indoor_temp_value, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Indoor_temp_value,"72");
lv_obj_set_style_text_color(ui_Indoor_temp_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Indoor_temp_value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Indoor_temp_value, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Indoor_temp_value, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Indoor_temp_value, lv_color_hex(0xFF9040), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Indoor_temp_value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Indoor_temp_value, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Indoor_temp_value, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Indoor_temp_value, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Indoor_temp_value, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Indoor_temp_value, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Indoor_temp_value, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temp_setpoint_container = lv_obj_create(ui_indoor_temps_container);
lv_obj_remove_style_all(ui_Temp_setpoint_container);
lv_obj_set_width( ui_Temp_setpoint_container, lv_pct(100));
lv_obj_set_height( ui_Temp_setpoint_container, LV_SIZE_CONTENT);   /// 28
lv_obj_set_x( ui_Temp_setpoint_container, 0 );
lv_obj_set_y( ui_Temp_setpoint_container, -1 );
lv_obj_set_align( ui_Temp_setpoint_container, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_Temp_setpoint_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Setpoint_row = lv_obj_create(ui_Temp_setpoint_container);
lv_obj_remove_style_all(ui_Setpoint_row);
lv_obj_set_width( ui_Setpoint_row, lv_pct(100));
lv_obj_set_height( ui_Setpoint_row, LV_SIZE_CONTENT);   /// 178
lv_obj_set_align( ui_Setpoint_row, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_Setpoint_row,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Setpoint_row, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Setpoint_row, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Heat_setpoint_container = lv_obj_create(ui_Setpoint_row);
lv_obj_remove_style_all(ui_Heat_setpoint_container);
lv_obj_set_width( ui_Heat_setpoint_container, 49);
lv_obj_set_height( ui_Heat_setpoint_container, 35);
lv_obj_set_align( ui_Heat_setpoint_container, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Heat_setpoint_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Heat_symbol = lv_label_create(ui_Heat_setpoint_container);
lv_obj_set_width( ui_Heat_symbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Heat_symbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Heat_symbol, 0 );
lv_obj_set_y( ui_Heat_symbol, 1 );
lv_obj_set_align( ui_Heat_symbol, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Heat_symbol,"");
lv_obj_set_style_text_color(ui_Heat_symbol, lv_color_hex(0xFF9040), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Heat_symbol, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Heat_symbol, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Heat_setpoint = lv_label_create(ui_Heat_setpoint_container);
lv_obj_set_width( ui_Heat_setpoint, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Heat_setpoint, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Heat_setpoint, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Heat_setpoint,"68");
lv_obj_set_style_text_color(ui_Heat_setpoint, lv_color_hex(0xFF9040), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Heat_setpoint, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Heat_setpoint, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cool_setpoint_container = lv_obj_create(ui_Setpoint_row);
lv_obj_remove_style_all(ui_Cool_setpoint_container);
lv_obj_set_width( ui_Cool_setpoint_container, 49);
lv_obj_set_height( ui_Cool_setpoint_container, 35);
lv_obj_set_align( ui_Cool_setpoint_container, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Cool_setpoint_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Cool_symbol = lv_label_create(ui_Cool_setpoint_container);
lv_obj_set_width( ui_Cool_symbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Cool_symbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Cool_symbol, 0 );
lv_obj_set_y( ui_Cool_symbol, 1 );
lv_obj_set_align( ui_Cool_symbol, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Cool_symbol,"");
lv_obj_set_style_text_color(ui_Cool_symbol, lv_color_hex(0x4CAFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Cool_symbol, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Cool_symbol, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cool_setpoint = lv_label_create(ui_Cool_setpoint_container);
lv_obj_set_width( ui_Cool_setpoint, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Cool_setpoint, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Cool_setpoint, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Cool_setpoint,"72");
lv_obj_set_style_text_color(ui_Cool_setpoint, lv_color_hex(0x4CAFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Cool_setpoint, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Cool_setpoint, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temp_header = lv_label_create(ui_Indoor_Temp);
lv_obj_set_width( ui_Temp_header, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temp_header, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Temp_header, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Temp_header,"TEMP (°F)");
lv_obj_set_style_text_color(ui_Temp_header, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Temp_header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temp_header, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Indoor_co2 = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_Indoor_co2);
lv_obj_set_width( ui_Indoor_co2, 118);
lv_obj_set_height( ui_Indoor_co2, 140);
lv_obj_set_x( ui_Indoor_co2, -10 );
lv_obj_set_y( ui_Indoor_co2, 0 );
lv_obj_set_align( ui_Indoor_co2, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Indoor_co2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_co2_header = lv_label_create(ui_Indoor_co2);
lv_obj_set_width( ui_co2_header, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_co2_header, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_co2_header, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_co2_header,"CO2 (PPM)");
lv_obj_set_style_text_color(ui_co2_header, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_co2_header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_co2_header, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_co2_container = lv_obj_create(ui_Indoor_co2);
lv_obj_remove_style_all(ui_co2_container);
lv_obj_set_height( ui_co2_container, 108);
lv_obj_set_width( ui_co2_container, lv_pct(100));
lv_obj_set_align( ui_co2_container, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_co2_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_co2_value = lv_label_create(ui_co2_container);
lv_obj_set_width( ui_co2_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_co2_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_co2_value, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_co2_value,"1234");
lv_obj_set_style_text_font(ui_co2_value, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_co2_value, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_co2_value, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_co2_value, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_co2_value, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_co2_setpoint_container = lv_obj_create(ui_co2_container);
lv_obj_remove_style_all(ui_co2_setpoint_container);
lv_obj_set_width( ui_co2_setpoint_container, 77);
lv_obj_set_height( ui_co2_setpoint_container, 35);
lv_obj_set_align( ui_co2_setpoint_container, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_co2_setpoint_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_co2_symbol = lv_label_create(ui_co2_setpoint_container);
lv_obj_set_width( ui_co2_symbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_co2_symbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_co2_symbol, 0 );
lv_obj_set_y( ui_co2_symbol, 1 );
lv_obj_set_align( ui_co2_symbol, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_co2_symbol,"");
lv_obj_set_style_text_font(ui_co2_symbol, &ui_font_MaterialSymbols18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_co2_target_value = lv_label_create(ui_co2_setpoint_container);
lv_obj_set_width( ui_co2_target_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_co2_target_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_co2_target_value, LV_ALIGN_RIGHT_MID );
lv_label_set_long_mode(ui_co2_target_value,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_co2_target_value,"1234");
lv_obj_set_style_text_font(ui_co2_target_value, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Fan, ui_event_Fan, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_indoor_temps_container, ui_event_indoor_temps_container, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_co2_container, ui_event_co2_container, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);

}
