// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ui

#include "../ui.h"

void ui_Restart_screen_init(void)
{
ui_Restart = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Restart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_boot_message1 = lv_label_create(ui_Restart);
lv_obj_set_width( ui_boot_message1, 216);
lv_obj_set_height( ui_boot_message1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_boot_message1, LV_ALIGN_CENTER );
lv_label_set_text(ui_boot_message1,"RESTARTING TO UPDATE CONFIGURATION");
lv_obj_set_style_text_color(ui_boot_message1, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_boot_message1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_boot_message1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_boot_message1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
