// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: ui

#include "../ui.h"

void ui_Temp_offsets_screen_init(void)
{
ui_Temp_offsets = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Temp_offsets, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Temp_offsets,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Temp_offsets, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_pad_left(ui_Temp_offsets, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Temp_offsets, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Temp_offsets, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Temp_offsets, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Temp_offsets, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Temp_offsets, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Thermostat_setting_header3 = ui_Setting_header_create(ui_Temp_offsets);
lv_obj_set_x( ui_Thermostat_setting_header3, 0 );
lv_obj_set_y( ui_Thermostat_setting_header3, 0 );

lv_label_set_text(ui_comp_get_child(ui_Thermostat_setting_header3, UI_COMP_SETTING_HEADER_SETTING_TITLE),"TEMP OFFSETS");





ui_Container7 = lv_obj_create(ui_Temp_offsets);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, 300);
lv_obj_set_height( ui_Container7, 190);
lv_obj_set_x( ui_Container7, 0 );
lv_obj_set_y( ui_Container7, -6 );
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_indoor_offset_container = lv_obj_create(ui_Container7);
lv_obj_remove_style_all(ui_indoor_offset_container);
lv_obj_set_height( ui_indoor_offset_container, 170);
lv_obj_set_width( ui_indoor_offset_container, LV_SIZE_CONTENT);  /// 2
lv_obj_set_align( ui_indoor_offset_container, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_indoor_offset_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_indoor_offset_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_indoor_offset_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_indoor_offset_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_indoor_offset_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_indoor_offset_container, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_opa(ui_indoor_offset_container, 60, LV_PART_MAIN| LV_STATE_DISABLED);

ui_Label30 = lv_label_create(ui_indoor_offset_container);
lv_obj_set_width( ui_Label30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label30, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label30,"INDOOR");
lv_obj_set_style_text_align(ui_Label30, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_indoor_offset = lv_roller_create(ui_indoor_offset_container);
lv_roller_set_options( ui_indoor_offset, "-5.0\n-4.9\n-4.8\n-4.7\n-4.6\n-4.5\n-4.4\n-4.3\n-4.2\n-4.1\n-4.0\n-3.9\n-3.8\n-3.7\n-3.6\n-3.5\n-3.4\n-3.3\n-3.2\n-3.1\n-3.0\n-2.9\n-2.8\n-2.7\n-2.6\n-2.5\n-2.4\n-2.3\n-2.2\n-2.1\n-2.0\n-1.9\n-1.8\n-1.7\n-1.6\n-1.5\n-1.4\n-1.3\n-1.2\n-1.1\n-1.0\n-0.9\n-0.8\n-0.7\n-0.6\n-0.5\n-0.4\n-0.3\n-0.2\n-0.1\n0.0\n+0.1\n+0.2\n+0.3\n+0.4\n+0.5\n+0.6\n+0.7\n+0.8\n+0.9\n+1.0\n+1.1\n+1.2\n+1.3\n+1.4\n+1.5\n+1.6\n+1.7\n+1.8\n+1.9\n+2.0\n+2.1\n+2.2\n+2.3\n+2.4\n+2.5\n+2.6\n+2.7\n+2.8\n+2.9\n+3.0\n+3.1\n+3.2\n+3.3\n+3.4\n+3.5\n+3.6\n+3.7\n+3.8\n+3.9\n+4.0\n+4.1\n+4.2\n+4.3\n+4.4\n+4.5\n+4.6\n+4.7\n+4.8\n+4.9\n+5.0", LV_ROLLER_MODE_NORMAL );
lv_roller_set_selected( ui_indoor_offset, 50, LV_ANIM_OFF);
lv_obj_set_height( ui_indoor_offset, 87);
lv_obj_set_width( ui_indoor_offset, LV_SIZE_CONTENT);  /// 50
lv_obj_set_align( ui_indoor_offset, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_indoor_offset, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_indoor_offset, lv_color_hex(0x44474C), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_indoor_offset, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_indoor_offset_label = lv_label_create(ui_indoor_offset_container);
lv_obj_set_width( ui_indoor_offset_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_indoor_offset_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_indoor_offset_label, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_indoor_offset_label,"66.6°");
lv_obj_set_style_text_color(ui_indoor_offset_label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_indoor_offset_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_indoor_offset_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fan_offset_divider = lv_obj_create(ui_Container7);
lv_obj_set_width( ui_fan_offset_divider, 1);
lv_obj_set_height( ui_fan_offset_divider, 140);
lv_obj_set_x( ui_fan_offset_divider, 0 );
lv_obj_set_y( ui_fan_offset_divider, -3 );
lv_obj_set_align( ui_fan_offset_divider, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_fan_offset_divider, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_fan_offset_divider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_fan_offset_divider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_fan_offset_divider, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_fan_offset_divider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_fan_offset_divider, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_fan_offset_divider, LV_BORDER_SIDE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fan_offset_container = lv_obj_create(ui_Container7);
lv_obj_remove_style_all(ui_fan_offset_container);
lv_obj_set_height( ui_fan_offset_container, 179);
lv_obj_set_width( ui_fan_offset_container, LV_SIZE_CONTENT);  /// 2
lv_obj_set_align( ui_fan_offset_container, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_fan_offset_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_fan_offset_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fan_offset_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fan_offset_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fan_offset_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_fan_offset_container, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_opa(ui_fan_offset_container, 60, LV_PART_MAIN| LV_STATE_DISABLED);

ui_Label39 = lv_label_create(ui_fan_offset_container);
lv_obj_set_width( ui_Label39, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label39, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label39, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label39,"FAN");
lv_obj_set_style_text_align(ui_Label39, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fan_offset = lv_roller_create(ui_fan_offset_container);
lv_roller_set_options( ui_fan_offset, "-5.0\n-4.9\n-4.8\n-4.7\n-4.6\n-4.5\n-4.4\n-4.3\n-4.2\n-4.1\n-4.0\n-3.9\n-3.8\n-3.7\n-3.6\n-3.5\n-3.4\n-3.3\n-3.2\n-3.1\n-3.0\n-2.9\n-2.8\n-2.7\n-2.6\n-2.5\n-2.4\n-2.3\n-2.2\n-2.1\n-2.0\n-1.9\n-1.8\n-1.7\n-1.6\n-1.5\n-1.4\n-1.3\n-1.2\n-1.1\n-1.0\n-0.9\n-0.8\n-0.7\n-0.6\n-0.5\n-0.4\n-0.3\n-0.2\n-0.1\n0.0\n+0.1\n+0.2\n+0.3\n+0.4\n+0.5\n+0.6\n+0.7\n+0.8\n+0.9\n+1.0\n+1.1\n+1.2\n+1.3\n+1.4\n+1.5\n+1.6\n+1.7\n+1.8\n+1.9\n+2.0\n+2.1\n+2.2\n+2.3\n+2.4\n+2.5\n+2.6\n+2.7\n+2.8\n+2.9\n+3.0\n+3.1\n+3.2\n+3.3\n+3.4\n+3.5\n+3.6\n+3.7\n+3.8\n+3.9\n+4.0\n+4.1\n+4.2\n+4.3\n+4.4\n+4.5\n+4.6\n+4.7\n+4.8\n+4.9\n+5.0", LV_ROLLER_MODE_NORMAL );
lv_roller_set_selected( ui_fan_offset, 50, LV_ANIM_OFF);
lv_obj_set_height( ui_fan_offset, 87);
lv_obj_set_width( ui_fan_offset, LV_SIZE_CONTENT);  /// 50
lv_obj_set_align( ui_fan_offset, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_fan_offset, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_fan_offset, lv_color_hex(0x44474C), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_fan_offset, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_fan_offset_label = lv_label_create(ui_fan_offset_container);
lv_obj_set_width( ui_fan_offset_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fan_offset_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_fan_offset_label, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_fan_offset_label,"66.6°");
lv_obj_set_style_text_color(ui_fan_offset_label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_fan_offset_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_fan_offset_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_comp_get_child(ui_Thermostat_setting_header3, UI_COMP_SETTING_HEADER_SETTING_BACK_BUTTON), ui_event_Thermostat_setting_header3_Setting_back_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_comp_get_child(ui_Thermostat_setting_header3, UI_COMP_SETTING_HEADER_SETTING_ACCEPT_BUTTON), ui_event_Thermostat_setting_header3_Setting_accept_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_indoor_offset, ui_event_indoor_offset, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_fan_offset, ui_event_fan_offset, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Temp_offsets, ui_event_Temp_offsets, LV_EVENT_ALL, NULL);

}
