// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui

#include "../ui.h"

void ui_Thermostat_screen_init(void)
{
ui_Thermostat = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Thermostat, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Thermostat,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Thermostat, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_pad_left(ui_Thermostat, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Thermostat, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Thermostat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Thermostat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Thermostat, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Thermostat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Thermostat_setting_header = ui_Setting_header_create(ui_Thermostat);
lv_obj_set_x( ui_Thermostat_setting_header, 0 );
lv_obj_set_y( ui_Thermostat_setting_header, 0 );

lv_label_set_text(ui_comp_get_child(ui_Thermostat_setting_header, UI_COMP_SETTING_HEADER_SETTING_TITLE),"THERMOSTAT");





ui_Container1 = lv_obj_create(ui_Thermostat);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 300);
lv_obj_set_height( ui_Container1, 190);
lv_obj_set_x( ui_Container1, 0 );
lv_obj_set_y( ui_Container1, -6 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Override_heat_container = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_Override_heat_container);
lv_obj_set_height( ui_Override_heat_container, 150);
lv_obj_set_width( ui_Override_heat_container, LV_SIZE_CONTENT);  /// 2
lv_obj_set_align( ui_Override_heat_container, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Override_heat_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Override_heat_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Override_heat_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Override_heat_container, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Override_heat_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_Override_heat_container, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_opa(ui_Override_heat_container, 60, LV_PART_MAIN| LV_STATE_DISABLED);

ui_Heat_override_setpoint = lv_roller_create(ui_Override_heat_container);
lv_roller_set_options( ui_Heat_override_setpoint, "50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60\n61\n62\n63\n64\n65\n66\n67\n68\n69\n70\n71\n72\n73\n74", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Heat_override_setpoint, 100);
lv_obj_set_width( ui_Heat_override_setpoint, LV_SIZE_CONTENT);  /// 50
lv_obj_set_align( ui_Heat_override_setpoint, LV_ALIGN_TOP_MID );
lv_obj_set_style_text_font(ui_Heat_override_setpoint, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Heat_override_setpoint, lv_color_hex(0xFF9040), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Heat_override_setpoint, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Override_heat_container);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label3,"");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFF9040), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &ui_font_MaterialSymbols24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Override_cool_container = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_Override_cool_container);
lv_obj_set_height( ui_Override_cool_container, 150);
lv_obj_set_width( ui_Override_cool_container, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Override_cool_container, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Override_cool_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Override_cool_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Override_cool_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Override_cool_container, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Override_cool_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_Override_cool_container, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_opa(ui_Override_cool_container, 60, LV_PART_MAIN| LV_STATE_DISABLED);

ui_Label4 = lv_label_create(ui_Override_cool_container);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label4,"");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x4CAFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &ui_font_MaterialSymbols24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Cool_override_setpoint = lv_roller_create(ui_Override_cool_container);
lv_roller_set_options( ui_Cool_override_setpoint, "50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60\n61\n62\n63\n64\n65\n66\n67\n68\n69\n70\n71\n72\n73\n74", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Cool_override_setpoint, 100);
lv_obj_set_width( ui_Cool_override_setpoint, LV_SIZE_CONTENT);  /// 50
lv_obj_set_align( ui_Cool_override_setpoint, LV_ALIGN_TOP_MID );
lv_obj_set_style_text_font(ui_Cool_override_setpoint, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Cool_override_setpoint, lv_color_hex(0x4CAFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Cool_override_setpoint, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Divider1 = lv_obj_create(ui_Container1);
lv_obj_set_width( ui_Divider1, 1);
lv_obj_set_height( ui_Divider1, 155);
lv_obj_set_x( ui_Divider1, 0 );
lv_obj_set_y( ui_Divider1, -3 );
lv_obj_set_align( ui_Divider1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Divider1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Divider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Divider1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Divider1, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Divider1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Divider1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Divider1, LV_BORDER_SIDE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Schedule_buttons = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_Schedule_buttons);
lv_obj_set_height( ui_Schedule_buttons, 165);
lv_obj_set_width( ui_Schedule_buttons, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Schedule_buttons, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Schedule_buttons,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Schedule_buttons, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Schedule_buttons, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_schedule_button = lv_btn_create(ui_Schedule_buttons);
lv_obj_set_width( ui_schedule_button, 120);
lv_obj_set_height( ui_schedule_button, 40);
lv_obj_set_align( ui_schedule_button, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_schedule_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_schedule_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_schedule_button, lv_color_hex(0x44474C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_schedule_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_schedule_button, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_schedule_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_schedule_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_schedule_button);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"SCHEDULE");
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ac_button_container = lv_obj_create(ui_Schedule_buttons);
lv_obj_remove_style_all(ui_ac_button_container);
lv_obj_set_width( ui_ac_button_container, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_ac_button_container, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_ac_button_container, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ac_button_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_use_ac_button = lv_btn_create(ui_ac_button_container);
lv_obj_set_width( ui_use_ac_button, 120);
lv_obj_set_height( ui_use_ac_button, 40);
lv_obj_set_align( ui_use_ac_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_use_ac_button, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_use_ac_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_use_ac_button, lv_color_hex(0x44474C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_use_ac_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_use_ac_button, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_use_ac_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_use_ac_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_use_ac_button);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"USE A/C");
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_stop_ac_button = lv_btn_create(ui_ac_button_container);
lv_obj_set_width( ui_stop_ac_button, 120);
lv_obj_set_height( ui_stop_ac_button, 40);
lv_obj_set_align( ui_stop_ac_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_stop_ac_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_stop_ac_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_stop_ac_button, lv_color_hex(0x44474C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_stop_ac_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_stop_ac_button, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_stop_ac_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_stop_ac_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_stop_ac_button);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"A/C OFF");
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_allow_ac_button = lv_btn_create(ui_ac_button_container);
lv_obj_set_width( ui_allow_ac_button, 120);
lv_obj_set_height( ui_allow_ac_button, 40);
lv_obj_set_align( ui_allow_ac_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_allow_ac_button, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_allow_ac_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_allow_ac_button, lv_color_hex(0x44474C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_allow_ac_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_allow_ac_button, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_allow_ac_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_allow_ac_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label22 = lv_label_create(ui_allow_ac_button);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"ALLOW A/C");
lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_power_button_container = lv_obj_create(ui_Schedule_buttons);
lv_obj_remove_style_all(ui_power_button_container);
lv_obj_set_width( ui_power_button_container, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_power_button_container, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_power_button_container, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_power_button_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_off_button = lv_btn_create(ui_power_button_container);
lv_obj_set_width( ui_off_button, 120);
lv_obj_set_height( ui_off_button, 40);
lv_obj_set_align( ui_off_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_off_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_off_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_off_button, lv_color_hex(0x44474C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_off_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_off_button, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_off_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_off_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_off_button);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"SYSTEM OFF");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_on_button = lv_btn_create(ui_power_button_container);
lv_obj_set_width( ui_on_button, 120);
lv_obj_set_height( ui_on_button, 40);
lv_obj_set_align( ui_on_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_on_button, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_on_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_on_button, lv_color_hex(0x44474C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_on_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_on_button, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_on_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_on_button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_on_button);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"ON");
lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_comp_get_child(ui_Thermostat_setting_header, UI_COMP_SETTING_HEADER_SETTING_BACK_BUTTON), ui_event_Thermostat_setting_header_Setting_back_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_comp_get_child(ui_Thermostat_setting_header, UI_COMP_SETTING_HEADER_SETTING_ACCEPT_BUTTON), ui_event_Thermostat_setting_header_Setting_accept_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_schedule_button, ui_event_schedule_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_use_ac_button, ui_event_use_ac_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_stop_ac_button, ui_event_stop_ac_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_allow_ac_button, ui_event_allow_ac_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_off_button, ui_event_off_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_on_button, ui_event_on_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Thermostat, ui_event_Thermostat, LV_EVENT_ALL, NULL);

}
