// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui

#include "../ui.h"

void ui_Wifi_screen_init(void)
{
ui_Wifi = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Wifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Wifi, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Wifi, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Wifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Wifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Setting_header3 = ui_Setting_header_create(ui_Wifi);
lv_obj_set_x( ui_Setting_header3, 0 );
lv_obj_set_y( ui_Setting_header3, 0 );

lv_label_set_text(ui_comp_get_child(ui_Setting_header3, UI_COMP_SETTING_HEADER_SETTING_TITLE),"WIFI");





ui_Container8 = lv_obj_create(ui_Wifi);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_width( ui_Container8, 300);
lv_obj_set_height( ui_Container8, LV_SIZE_CONTENT);   /// 200
lv_obj_set_x( ui_Container8, 0 );
lv_obj_set_y( ui_Container8, 50 );
lv_obj_set_align( ui_Container8, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Container8,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container8, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ssid_container = lv_obj_create(ui_Container8);
lv_obj_remove_style_all(ui_ssid_container);
lv_obj_set_width( ui_ssid_container, 300);
lv_obj_set_height( ui_ssid_container, 45);
lv_obj_set_align( ui_ssid_container, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ssid_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label40 = lv_label_create(ui_ssid_container);
lv_obj_set_width( ui_Label40, 110);
lv_obj_set_height( ui_Label40, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label40, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label40,"SSID");
lv_obj_set_style_text_align(ui_Label40, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_ssid = lv_textarea_create(ui_ssid_container);
lv_obj_set_width( ui_wifi_ssid, 170);
lv_obj_set_height( ui_wifi_ssid, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_wifi_ssid, LV_ALIGN_RIGHT_MID );
lv_textarea_set_one_line(ui_wifi_ssid,true);
lv_obj_set_style_text_align(ui_wifi_ssid, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_password_container = lv_obj_create(ui_Container8);
lv_obj_remove_style_all(ui_password_container);
lv_obj_set_width( ui_password_container, 300);
lv_obj_set_height( ui_password_container, 45);
lv_obj_set_align( ui_password_container, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_password_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label41 = lv_label_create(ui_password_container);
lv_obj_set_width( ui_Label41, 110);
lv_obj_set_height( ui_Label41, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label41, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label41,"PASSWORD");
lv_obj_set_style_text_align(ui_Label41, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_password = lv_textarea_create(ui_password_container);
lv_obj_set_width( ui_wifi_password, 170);
lv_obj_set_height( ui_wifi_password, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_wifi_password, LV_ALIGN_RIGHT_MID );
lv_textarea_set_one_line(ui_wifi_password,true);
lv_obj_set_style_text_align(ui_wifi_password, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_log_name_container = lv_obj_create(ui_Container8);
lv_obj_remove_style_all(ui_log_name_container);
lv_obj_set_width( ui_log_name_container, 300);
lv_obj_set_height( ui_log_name_container, 45);
lv_obj_set_align( ui_log_name_container, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_log_name_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label42 = lv_label_create(ui_log_name_container);
lv_obj_set_width( ui_Label42, 110);
lv_obj_set_height( ui_Label42, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label42, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label42,"LOG NAME");
lv_obj_set_style_text_align(ui_Label42, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label42, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_log_name = lv_textarea_create(ui_log_name_container);
lv_obj_set_width( ui_log_name, 170);
lv_obj_set_height( ui_log_name, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_log_name, LV_ALIGN_RIGHT_MID );
lv_textarea_set_one_line(ui_log_name,true);
lv_obj_set_style_text_align(ui_log_name, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_wifi_keyboard = lv_keyboard_create(ui_Wifi);
lv_obj_set_width( ui_wifi_keyboard, 300);
lv_obj_set_height( ui_wifi_keyboard, 120);
lv_obj_set_align( ui_wifi_keyboard, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_wifi_keyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_add_event_cb(ui_comp_get_child(ui_Setting_header3, UI_COMP_SETTING_HEADER_SETTING_BACK_BUTTON), ui_event_Setting_header3_Setting_back_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_comp_get_child(ui_Setting_header3, UI_COMP_SETTING_HEADER_SETTING_ACCEPT_BUTTON), ui_event_Setting_header3_Setting_accept_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Wifi, ui_event_Wifi, LV_EVENT_ALL, NULL);

}
